import * as path from 'node:path';
import { DocsSiteError } from '../DocsSiteError';
import { ProseLoader } from '../manifest/ProseLoader';
import { RenderedSite } from '../render/SitePage';
import { SiteRenderer } from '../render/SiteRenderer';
import { SiteWriter } from '../emit/SiteWriter';
import { SpecLoader } from '../spec/SpecLoader';
import { SpecReader } from '../spec/SpecReader';

const SPEC = '--spec';
const PROSE = '--prose';
const OUT = '--out';
const PORT = '--port';
const SERVE = '--serve';
const HELP = '--help';

const VALUE_FLAGS = [SPEC, PROSE, OUT, PORT];
const BARE_FLAGS = [SERVE, HELP];

export const USAGE = [
    'wp-docs-site --spec <openapi.json> [--prose <dir>] --out <dir> [--serve] [--port <n>]',
    '',
    'Renders a static, three-pane API reference site: one PRE-RENDERED HTML file per URL, so a deep',
    'link resolves without JavaScript and the output is a folder any static host serves.',
    '',
    '  --spec    an OpenAPI 3.0 or 3.1 JSON document. Any conforming document — this renderer does',
    '            not require the document to have been generated by webpieces.',
    '  --prose   a directory holding docs.manifest.json and the markdown it names, in ITS order.',
    '  --out     where to write the site. Nothing in it is deleted.',
    '  --serve   after writing, preview the result on 127.0.0.1 and nothing else. It is a PREVIEW:',
    '            not hardened, not authenticated, and not a way to host the site.',
    '  --port    the preview port. 0, the default, asks the operating system for a free one.',
].join('\n');

/** What one run produced, so a caller can print it or assert on it. */
export class CliResult {
    constructor(
        readonly written: readonly string[],
        readonly site: RenderedSite,
        readonly outDir: string,
        readonly serve: boolean,
        readonly port: number,
    ) {}
}

/**
 * `wp-docs-site`'s argument parsing and composition, with NO process-level concerns in it — no
 * `process.exit`, no `console` — so the suite exercises the whole command exactly as a user runs it.
 *
 * `--spec` and `--out` are REQUIRED and have no defaults. A defaulted `--out` writes a site
 * somewhere the caller did not name; a defaulted `--spec` documents whichever service the command
 * happened to start in.
 */
export class DocsSiteCli {
    private readonly specs = new SpecLoader();
    private readonly reader = new SpecReader();
    private readonly prose = new ProseLoader();
    private readonly renderer = new SiteRenderer();
    private readonly writer = new SiteWriter();

    /** @param argv the arguments AFTER the program name. @param cwd what relative paths resolve against. */
    run(argv: readonly string[], cwd: string): CliResult {
        const spec = this.valueOf(argv, SPEC);
        const out = this.valueOf(argv, OUT);
        if (spec === undefined || out === undefined) {
            throw new DocsSiteError(
                `wp-docs-site needs both ${SPEC} and ${OUT}`,
                'wp-docs-site',
                `Run: wp-docs-site ${SPEC} <openapi.json> ${OUT} <dir>`,
            );
        }
        const proseDir = this.proseDirOf(argv, cwd);
        const document = this.specs.load(path.resolve(cwd, spec));
        const site = this.renderer.render(
            this.reader.read(document),
            this.prose.load(proseDir),
            this.prose.titleOf(proseDir),
        );
        const outDir = path.resolve(cwd, out);
        return new CliResult(
            this.writer.write(outDir, site),
            site,
            outDir,
            argv.includes(SERVE),
            this.portOf(argv),
        );
    }

    wantsHelp(argv: readonly string[]): boolean {
        return argv.includes(HELP);
    }

    private proseDirOf(argv: readonly string[], cwd: string): string | undefined {
        const declared = this.valueOf(argv, PROSE);
        return declared === undefined ? undefined : path.resolve(cwd, declared);
    }

    private portOf(argv: readonly string[]): number {
        const declared = this.valueOf(argv, PORT);
        if (declared === undefined) {
            return 0;
        }
        const port = Number(declared);
        if (!Number.isInteger(port) || port < 0 || port > 65535) {
            throw new DocsSiteError(
                `${PORT} '${declared}' is not a port number`,
                'wp-docs-site',
                `${PORT} takes a whole number from 0 to 65535. 0 asks the operating system for a free one.`,
            );
        }
        return port;
    }

    /**
     * The value after a flag. An UNKNOWN flag is refused rather than ignored: a mistyped `--spce`
     * would otherwise fall through to "needs both flags", which sends the reader looking at the
     * wrong thing.
     */
    private valueOf(argv: readonly string[], flag: string): string | undefined {
        for (let i = 0; i < argv.length; i++) {
            const argument = argv[i]!;
            if (argument === flag) {
                return argv[i + 1];
            }
            if (
                argument.startsWith('--') &&
                !VALUE_FLAGS.includes(argument) &&
                !BARE_FLAGS.includes(argument)
            ) {
                throw new DocsSiteError(
                    `unknown flag '${argument}'`,
                    'wp-docs-site',
                    `wp-docs-site takes ${[...VALUE_FLAGS, ...BARE_FLAGS].join(', ')}, and nothing else.`,
                );
            }
        }
        return undefined;
    }
}
