import { PlatformHeader } from '@webpieces/http-api';

/**
 * Core framework headers for distributed tracing and request correlation.
 *
 * These are the minimal headers needed by the WebPieces framework for:
 * - Request tracking across services
 * - Distributed tracing
 * - Request correlation
 * - Metrics and monitoring
 *
 * Pattern inspired by Java MicroSvcHeader enum.
 */
export class WebpiecesCoreHeaders {
    /**
     * Unique ID for this request.
     * Generated by the server if not provided.
     * Used for distributed tracing and log correlation.
     */
    static readonly REQUEST_ID = new PlatformHeader(
        'x-request-id',
        true,  // transfer (propagate to downstream services)
        false, // not secured (it's just an ID)
        true   // use for metrics dimensions
    );

    /**
     * ID of the previous request in the call chain.
     * When service A calls service B, B receives A's REQUEST_ID as PREVIOUS_REQUEST_ID.
     * Used for building distributed trace trees.
     */
    static readonly PREVIOUS_REQUEST_ID = new PlatformHeader(
        'x-previous-request-id',
        true,
        false,
        false
    );

    /**
     * Correlation ID that spans multiple related requests.
     * Typically set by the API gateway or first service in the chain.
     * All services in the call chain use the same CORRELATION_ID.
     */
    static readonly CORRELATION_ID = new PlatformHeader(
        'x-correlation-id',
        true,
        false,
        true   // use for metrics dimensions
    );

    /**
     * Get all core headers as an array.
     * Used by WebpiecesModule to bind headers to DI container.
     *
     * @returns Array of all core platform headers
     */
    static getAllHeaders(): PlatformHeader[] {
        return [
            WebpiecesCoreHeaders.REQUEST_ID,
            WebpiecesCoreHeaders.PREVIOUS_REQUEST_ID,
            WebpiecesCoreHeaders.CORRELATION_ID,
        ];
    }
}
