import {
    GateDefinition,
    WEBPIECES_DISABLE,
    RULE_NAMES,
    ReviewJson,
    CK_PASS,
    CK_WARN,
    CK_OVERRIDDEN,
    CK_FAIL,
    CK_MISSING,
} from '@webpieces/rules-config';
import { injectable, bindingScopeValues } from 'inversify';

/**
 * Hidden marker on the FULL-DASHBOARD comment — the "1st comment" the PR description points at — so
 * finish PATCHes its own comment on every push instead of appending a new one, exactly like the checklist
 * comment (see ChecklistCommentRenderer, which owns the 2nd).
 *
 * This comment did not exist before the PR description became the git-log body: the dashboard WAS the
 * description. Moving it here is what keeps a risk table out of every squash commit on main.
 */
export const DETAIL_COMMENT_MARKER = '<!-- webpieces-pr-detail v1 -->';

/**
 * Footer on the full-dashboard comment. Names the tooling by REPO URL so a reader landing on a
 * generated comment in any consumer repo can find what generated it.
 *
 * It deliberately no longer asserts "build ran via nx affected — not self-attested": that sentence was
 * hard-coded and therefore wrong on every repo whose `buildCommand` is not nx. The build command is now
 * named for real, from config, in the PR-body footer — see {@link Dashboard.renderPrBody}.
 */
const DETAIL_COMMENT_FOOTER = 'Generated by https://github.com/deanhiller/webpieces-ts  wp-finish-upsert-pr';

/**
 * The last bullet of the PR description, and therefore of every squash commit body.
 *
 * Positional ("1st"/"2nd") on purpose — it is what a reader of `git log` can actually act on, far more
 * useful than naming an HTML marker they cannot see. On a PR opened by an OLDER release the checklist
 * comment already exists, so the dashboard comment lands second and this reads one off for that PR's
 * remaining life; it is cosmetic and self-corrects on the next PR.
 */
const DETAIL_POINTER = '(Full dashboard in 1st comment, reviewer checklist in 2nd — kept out of git log)';

export class GateResult {
    name: string;
    warningColor: string; // 'yellow' | 'red' — the color shown WHEN files matched (green is implicit)
    matchedFiles: string[];

    constructor(name: string, warningColor: string, matchedFiles: string[]) {
        this.name = name;
        this.warningColor = warningColor;
        this.matchedFiles = matchedFiles;
    }
}

// One row for a consumer review checklist the branch triggered. `status` is the resolved verdict (one of
// CK_PASS | CK_WARN | CK_OVERRIDDEN | CK_FAIL | CK_MISSING | CK_BAD_FORMAT); `detail` is the reviewer
// output / override justification. A row is always PASS/WARN/OVERRIDDEN by the time it renders — a failed,
// missing or unreadable verdict throws before the dashboard is built. Rendered into the PR body so the
// verdict reaches the server — the PR body is the artifact of the local flow that leaves the checkout
// (alongside the HMAC gate token that proves the flow ran).
export class ChecklistRow {
    title: string; // the checklist id (= reviewer subagent name)
    status: string; // CK_* verdict
    detail: string; // reviewer output / override justification (surfaced for OVERRIDDEN)

    constructor(title: string, status: string, detail = '') {
        this.title = title;
        this.status = status;
        this.detail = detail;
    }
}

/**
 * One severity bucket of the rolled-up **Checklists** dashboard row: its emoji, the words that describe it,
 * and which checklists landed in it. Data-only.
 *
 * A bucket knows whether it should NAME its members: the non-green ones do (a reader has to know WHICH
 * reviewer to go read), the passed bucket does not (a list of what went fine is noise on a one-line row).
 */
class RollupBucket {
    label: string; // 'blocking' | 'overridden' | 'with concerns' | 'passed'
    emoji: string;
    named: boolean; // list the checklist ids on the row, or report a bare count
    titles: string[];

    constructor(label: string, emoji: string, named: boolean) {
        this.label = label;
        this.emoji = emoji;
        this.named = named;
        this.titles = [];
    }
}

export class DisableCounts {
    webpiecesCount: number;
    eslintCount: number;
    webpiecesRules: string[];

    constructor(webpiecesCount: number, eslintCount: number, webpiecesRules: string[]) {
        this.webpiecesCount = webpiecesCount;
        this.eslintCount = eslintCount;
        this.webpiecesRules = webpiecesRules;
    }
}

export class DashboardInput {
    title: string;
    gateResults: GateResult[];
    disables: DisableCounts;
    buildPassed: boolean;
    forkPoint: string;
    featureHead: string;
    mainHead: string;
    review: ReviewJson; // AI-authored risk/violations/summary (from review.json)
    checklists: ChecklistRow[]; // consumer checklists this branch triggered; [] for non-adopting repos
    /**
     * `commands.pr-gate.buildCommand` VERBATIM, named in the PR-body footer so `git log` records WHICH
     * command vouched for the commit. Read from config rather than hard-coded because the footer used to
     * assert "build ran via nx affected" on every repo, including those whose buildCommand is not nx at
     * all. '' renders the footer without the parenthetical.
     */
    buildCommand: string;

    // eslint-disable-next-line @typescript-eslint/max-params
    constructor(
        title: string,
        gateResults: GateResult[],
        disables: DisableCounts,
        buildPassed: boolean,
        forkPoint: string,
        featureHead: string,
        mainHead: string,
        review: ReviewJson,
        checklists: ChecklistRow[] = [],
        buildCommand: string = '',
    ) {
        this.title = title;
        this.gateResults = gateResults;
        this.disables = disables;
        this.buildPassed = buildPassed;
        this.forkPoint = forkPoint;
        this.featureHead = featureHead;
        this.mainHead = mainHead;
        this.review = review;
        this.checklists = checklists;
        this.buildCommand = buildCommand;
    }
}

/** Renders the PR-gate dashboard markdown (gates × changed files, disables, risk, 3-point hashes). */
@injectable(bindingScopeValues.Singleton)
export class Dashboard {
    // Disabled gates are in-file examples (JSON has no comments) — skip them entirely.
    computeGateResults(gates: GateDefinition[], changedFiles: string[]): GateResult[] {
        return gates
            .filter((gate: GateDefinition): boolean => !gate.disabled)
            .map((gate: GateDefinition): GateResult => {
                const matched = changedFiles.filter((file: string): boolean =>
                    this.matchesAny(gate.patterns, file),
                );
                return new GateResult(gate.name, gate.warningColor, matched);
            });
    }

    // Count disables ADDED in this PR by scanning added (`+`) lines of the diff patch. Rule-aware:
    // reports which webpieces rules were disabled, using the canonical RULE_NAMES vocabulary.
    countAddedDisables(patch: string): DisableCounts {
        let webpiecesCount = 0;
        let eslintCount = 0;
        const rules = new Set<string>();
        const allRuleTokens = Object.keys(RULE_NAMES).map(
            (key: string): string => (RULE_NAMES as Record<string, string>)[key],
        );

        for (const line of patch.split('\n')) {
            if (!line.startsWith('+') || line.startsWith('+++')) continue;
            if (line.includes(WEBPIECES_DISABLE)) {
                webpiecesCount += 1;
                for (const token of allRuleTokens) {
                    if (line.includes(token)) rules.add(token);
                }
            }
            if (line.includes('eslint-disable')) eslintCount += 1;
        }
        return new DisableCounts(webpiecesCount, eslintCount, Array.from(rules).sort());
    }

    /**
     * The FULL dashboard — every row (green included), the whole summary, the 3-point hash points.
     *
     * This is the **1st PR comment**, not the PR description. It used to be the description, and that is
     * exactly what put it into main's history: GitHub's `squash_merge_commit_message: PR_BODY` copies the
     * description verbatim into the squash commit, so every `git log` entry carried the risk table, the
     * hash points and the gate token. The description now holds {@link renderPrBody}'s compact form, and
     * everything long-form lives here where a reader can open it and `git log` never sees it.
     *
     * Machine-facing content belongs HERE too — this comment carries the HMAC gate token. That is the
     * whole rule that keeps the description clean: an HTML comment is invisible in rendered markdown but
     * perfectly visible in `git log`, so nothing hidden may live in the description.
     */
    renderDetailComment(input: DashboardInput): string {
        const lines: string[] = [];
        lines.push('## 🚦 PR Gate Dashboard');
        lines.push('');
        for (const line of this.riskLines(input.review)) lines.push(line);
        lines.push(`**Build (nx affected):** ${input.buildPassed ? '🟢 Passed' : '🔴 Failed'}`);
        for (const result of input.gateResults) lines.push(this.gateLine(result));
        lines.push(this.disableLine(input.disables));
        const eslintEmoji =
            input.disables.eslintCount === 0 ? '🟢 No' : `🟡 ${input.disables.eslintCount} line(s)`;
        lines.push(`**ESLint Disables Added:** ${eslintEmoji}`);
        // ONE rolled-up row for ALL triggered consumer checklists — a worst-of colour and a count, sitting
        // with the other status rows. It used to be one row PER checklist, each inlining that checklist's
        // whole verdict/override paragraph: on a six-checklist PR that was the same ~90-word override
        // repeated six times, burying the signal rows above it — and every word of it was already in the
        // checklist COMMENT, per reviewer, in full. ALWAYS emitted, including the zero case: "no reviewer
        // looked at this PR" is a fact a reader must be told, and an absent row silently reads as a green
        // all-clear (see checklistRollupLine).
        lines.push(this.checklistRollupLine(input.checklists));
        lines.push('');
        if (input.review.summary.trim() !== '') {
            lines.push('### Summary');
            lines.push(input.review.summary.trim());
            lines.push('');
        }
        lines.push('### 🔍 3-Point Hash Points');
        lines.push(`- Fork point (A): \`${input.forkPoint.slice(0, 12)}\``);
        lines.push(`- Feature HEAD (B): \`${input.featureHead.slice(0, 12)}\``);
        lines.push(`- Main HEAD (C): \`${input.mainHead.slice(0, 12)}\``);
        lines.push('');
        lines.push(`<sub>🤖 ${DETAIL_COMMENT_FOOTER}</sub>`);
        return lines.join('\n');
    }

    /**
     * The PR DESCRIPTION — which is also, byte for byte, the squash-commit body that lands in main.
     *
     * ─── Why one string serves both ─────────────────────────────────────────────────────────────────
     * There used to be two: a long dashboard in the description and this compact form passed to
     * `gh pr merge --body-file`. That made the good `git log` reachable ONLY through an explicit
     * `--body-file` merge, because every other route (the GitHub Merge button, a bare `gh pr merge`)
     * takes its body from the repo's `squash_merge_commit_message`, and on `PR_BODY` that copied the
     * whole dashboard into history. Two repos ran that way for months.
     *
     * Making the DESCRIPTION the compact form inverts it: `PR_BODY` now yields exactly the right commit,
     * so the UI button, a bare `gh pr merge`, `wp-land-pr` and finish's own auto-merge all converge on
     * identical bytes. The consumer requirement is two repo settings — `squash_merge_commit_title:
     * PR_TITLE` and `squash_merge_commit_message: PR_BODY` — not a config key and not a command anyone
     * has to remember. That convergence is the point, and `pr-body-is-merge-body.spec.ts` pins it.
     *
     * ─── The shape, and why each part earns its line ────────────────────────────────────────────────
     * The URL leads, labelled `(for git log)` so nobody deletes it as redundant while reading the PR on
     * GitHub — on the page it is obviously the page you are on; in `git log` it is the only way back.
     * Then the risk score (always). Then ONLY the non-green flags: a commit log should surface what
     * stands out, and the green rows are in the 1st comment. The last bullet is always the pointer to
     * that comment, so a reader of main's history is never left thinking this is all there was. Then the
     * summary capped at 4 sentences, then the footer naming the build command that vouched for it.
     *
     * The hidden gate-token marker is appended AFTER this by the caller, so it is the very last line of
     * the description and therefore of the commit. It stays an HTML comment — invisible on the PR page,
     * visible in `git log` — which is a deliberate accepted trade: the alternative was reshaping a live
     * CI-critical surface that two consumer repos verify on every PR, to save one line of history.
     */
    renderPrBody(input: DashboardInput, prUrl: string): string {
        const lines: string[] = [];
        if (prUrl !== '') {
            lines.push(`${prUrl} (for git log)`);
            lines.push('');
        }
        lines.push(
            `Risk: ${this.riskBar(input.review.riskScore)} ${input.review.riskScore}/100 ${input.review.riskEmoji} (${input.review.riskLevel})`,
        );
        lines.push('');
        const flags = this.nonGreenFlags(input);
        lines.push(flags.length === 0 ? 'Flags: 🟢 all green' : 'Flags (non-green):');
        for (const flag of flags) lines.push(`- ${flag}`);
        // ALWAYS the last bullet, green case included. Without it the compact body reads as the whole
        // record, and the reader never learns that every green row, the full summary and each reviewer's
        // output are one click away.
        lines.push(`- ${DETAIL_POINTER}`);
        const summary = this.firstSentences(input.review.summary.trim(), 4);
        if (summary !== '') {
            lines.push('');
            lines.push(summary);
        }
        lines.push('');
        lines.push(this.prBodyFooter(input.buildCommand));
        return lines.join('\n');
    }

    /**
     * The footer, naming the build command from `commands.pr-gate.buildCommand` VERBATIM.
     *
     * No backticks: this string's primary home is `git log` in a terminal, where markdown ticks are
     * literal punctuation. "run locally" is the honest claim — this is the LOCAL gate's receipt, and the
     * server-side proof is the gate token in the 1st comment, not this sentence.
     */
    private prBodyFooter(buildCommand: string): string {
        const cmd = buildCommand.trim();
        const ran = cmd === '' ? '' : ` (${cmd} run locally)`;
        return `Generated by webpieces-ts wp-finish-upsert-pr${ran}`;
    }

    // Every dashboard row that is NOT green, as a flat bullet list for the commit body. Green rows
    // (build passed, gate did not match, zero disables/violations) are intentionally omitted.
    private nonGreenFlags(input: DashboardInput): string[] {
        const flags: string[] = [];
        if (!input.buildPassed) flags.push('Build (nx affected): 🔴 Failed');
        if (input.review.violations.length > 0)
            flags.push(`Pattern Violations: 🟡 ${input.review.violations.length} violation(s)`);
        for (const result of input.gateResults) {
            if (result.matchedFiles.length === 0) continue;
            const emoji = result.warningColor === 'red' ? '🔴' : '🟡';
            flags.push(`${result.name}: ${emoji} ${result.matchedFiles.length} file(s)`);
        }
        if (input.disables.webpiecesCount > 0) {
            const which =
                input.disables.webpiecesRules.length > 0
                    ? ` — ${input.disables.webpiecesRules.join(', ')}`
                    : '';
            flags.push(
                `Webpieces Disables Added: 🟡 ${input.disables.webpiecesCount} line(s)${which}`,
            );
        }
        if (input.disables.eslintCount > 0)
            flags.push(`ESLint Disables Added: 🟡 ${input.disables.eslintCount} line(s)`);
        // A triggered checklist is noteworthy in main's history — carry each into the commit body.
        for (const row of input.checklists) {
            flags.push(`Checklist — ${row.title}: ${this.checklistStatusText(row)}`);
        }
        return flags;
    }

    // Emoji + words for a checklist verdict, shared by the dashboard row and the commit-body flag.
    // Every state is matched EXPLICITLY and the fallthrough names the status it did not recognize. The
    // previous `return '🟢 passed'` fallthrough meant any newly-added verdict rendered as a clean pass on
    // both the PR body and main's commit history until someone noticed — exactly the wrong default.
    private checklistStatusText(row: ChecklistRow): string {
        if (row.status === CK_OVERRIDDEN) {
            const why = row.detail.trim() !== '' ? ` — override: ${row.detail.trim()}` : '';
            return `🟠 OVERRIDDEN${why}`;
        }
        if (row.status === CK_WARN) return '🟡 passed with concerns';
        if (row.status === CK_FAIL) return '🔴 FAILED review';
        if (row.status === CK_MISSING) return '⚪ not reviewed';
        if (row.status === CK_PASS) return '🟢 passed';
        return `⚪ unknown verdict (${row.status})`;
    }

    // First `max` sentences of `text`. A sentence ends at `. ! ?` ONLY when followed by whitespace or
    // end-of-string, so interior dots in filenames/paths/versions (dependencies.json, runtime-graph.ts,
    // 0.4.447) do NOT split — and, unlike a greedy `[^.!?]+` regex, no text is ever dropped when such a
    // dot appears (that footgun silently deleted the run of prose up to the next real boundary). Keeps
    // the commit body scannable; the full summary still lives in the PR-body dashboard.
    private firstSentences(text: string, max: number): string {
        if (text === '') return '';
        const sentences: string[] = [];
        let start = 0;
        for (let i = 0; i < text.length && sentences.length < max; i++) {
            const ch = text[i];
            const isTerminator = ch === '.' || ch === '!' || ch === '?';
            const next = text[i + 1];
            if (isTerminator && (next === undefined || /\s/.test(next))) {
                sentences.push(text.slice(start, i + 1).trim());
                start = i + 1;
            }
        }
        // Trailing text with no terminator still counts as a sentence (up to the cap).
        if (sentences.length < max && start < text.length) {
            const tail = text.slice(start).trim();
            if (tail !== '') sentences.push(tail);
        }
        return sentences.join(' ').trim();
    }

    // Self-contained glob matcher (** , * , ?) so pr-gate needs no extra runtime dependency.
    private globToRegex(pattern: string): RegExp {
        let re = '';
        let i = 0;
        while (i < pattern.length) {
            const ch = pattern[i];
            if (ch === '*' && pattern[i + 1] === '*') {
                re += '.*';
                i += 2;
                if (pattern[i] === '/') i += 1;
                continue;
            }
            if (ch === '*') {
                re += '[^/]*';
                i += 1;
                continue;
            }
            if (ch === '?') {
                re += '[^/]';
                i += 1;
                continue;
            }
            if ('.+^$(){}|[]\\'.includes(ch)) {
                re += '\\' + ch;
                i += 1;
                continue;
            }
            re += ch;
            i += 1;
        }
        return new RegExp('^' + re + '$');
    }

    private matchesAny(patterns: string[], file: string): boolean {
        for (const pattern of patterns) {
            if (this.globToRegex(pattern).test(file)) return true;
        }
        return false;
    }

    private gateLine(result: GateResult): string {
        if (result.matchedFiles.length === 0) return `**${result.name}:** 🟢 No`;
        const emoji = result.warningColor === 'red' ? '🔴' : '🟡';
        return `**${result.name}:** ${emoji} Yes (${result.matchedFiles.length} file(s))`;
    }

    /**
     * The ONE rolled-up **Checklists:** row, coloured worst-of across every checklist that ran, in the same
     * shape as its neighbours (`**Build (nx affected):** 🟢 Passed`). Counts and names only — never a line
     * of reviewer output or override justification, which is the whole reason this row exists.
     */
    private checklistRollupLine(rows: readonly ChecklistRow[]): string {
        const buckets = this.rollupBuckets(rows);
        const filled = buckets.filter((b: RollupBucket): boolean => b.titles.length > 0);
        // NO reviewer ran ⇒ the SKIPPED icon, never green. Green claims something was checked and came back
        // clean; ⚪ says nobody looked, which is what a reader has to be able to tell apart at a glance.
        if (filled.length === 0) {
            return '**Checklists:** ⚪ 0 ran — no review checklist matched this PR · see the checklist comment';
        }
        const allPassed = filled.length === 1 && !filled[0].named;
        const detail = allPassed
            ? 'all passed'
            : filled.map((b: RollupBucket): string => this.bucketPhrase(b)).join(', ');
        return `**Checklists:** ${filled[0].emoji} ${rows.length} ran — ${detail} · per-checklist detail in the checklist comment`;
    }

    /**
     * The four severity buckets, WORST FIRST, so `filled[0]` is the roll-up colour: red beats orange beats
     * yellow beats green. The colours are the same vocabulary the comment already uses (see verdictEmoji).
     *
     * OVERRIDDEN is deliberately NOT folded into passed: an override is a human knowingly accepting a red
     * verdict, and a dashboard that painted that green would hide the single most review-worthy thing on
     * the PR. The blocking bucket is the FALLTHROUGH — CK_FAIL, CK_MISSING, CK_BAD_FORMAT and any verdict
     * added later all land there, matching review.json's own "not pass|warn|overridden ⇒ refuse" rule
     * rather than a second list that could silently drift green.
     */
    private rollupBuckets(rows: readonly ChecklistRow[]): RollupBucket[] {
        const blocking = new RollupBucket('blocking', '🔴', true);
        const overridden = new RollupBucket('overridden', '🟠', true);
        const warned = new RollupBucket('with concerns', '🟡', true);
        const passed = new RollupBucket('passed', '🟢', false);
        for (const row of rows) {
            if (row.status === CK_PASS) passed.titles.push(row.title);
            else if (row.status === CK_WARN) warned.titles.push(row.title);
            else if (row.status === CK_OVERRIDDEN) overridden.titles.push(row.title);
            else blocking.titles.push(row.title);
        }
        return [blocking, overridden, warned, passed];
    }

    // `2 overridden (a, b)` for the buckets a reviewer must act on; a bare `3 passed` for the one they need
    // no list of. Names are capped so a many-checklist repo still gets a ONE-LINE row.
    private bucketPhrase(bucket: RollupBucket): string {
        if (!bucket.named) return `${bucket.titles.length} ${bucket.label}`;
        return `${bucket.titles.length} ${bucket.label} (${this.compactNames(bucket.titles)})`;
    }

    private compactNames(titles: readonly string[]): string {
        const max = 4;
        if (titles.length <= max) return titles.join(', ');
        return `${titles.slice(0, max).join(', ')} +${titles.length - max} more`;
    }

    // 10-cell risk bar colored by band (🟩 ≤25, 🟨 ≤50, 🟧 ≤75, 🟥 >75), at least one filled cell.
    private riskBar(score: number): string {
        const clamped = Math.max(0, Math.min(100, score));
        const cell = clamped <= 25 ? '🟩' : clamped <= 50 ? '🟨' : clamped <= 75 ? '🟧' : '🟥';
        const filled = Math.max(1, Math.min(10, Math.round(clamped / 10)));
        return cell.repeat(filled) + '⬜'.repeat(10 - filled);
    }

    // RISK section (the AI half): Risk Score bar, Risk Level, Pattern Violations.
    private riskLines(review: ReviewJson): string[] {
        const violations = review.violations.length;
        const violationLine = violations === 0 ? '🟢 No' : `🟡 Yes (${violations} violation(s))`;
        return [
            `**Risk Score:** ${this.riskBar(review.riskScore)} **${review.riskScore}/100** ${review.riskEmoji}`,
            `**Risk Level:** ${review.riskEmoji} **${review.riskLevel}**`,
            `**Pattern Violations:** ${violationLine}`,
        ];
    }

    private disableLine(disables: DisableCounts): string {
        if (disables.webpiecesCount === 0) return '**Webpieces Disables Added:** 🟢 No';
        const which =
            disables.webpiecesRules.length > 0 ? ` — ${disables.webpiecesRules.join(', ')}` : '';
        return `**Webpieces Disables Added:** 🟡 ${disables.webpiecesCount} line(s)${which}`;
    }
}
