import { JsonNode } from './JsonNode';

/**
 * The model this package renders. It is read from a document STRUCTURALLY (see {@link JsonNode}), so
 * it is deliberately NOT `@webpieces/openapi-generator`'s document classes even though it looks like
 * them: a compile-time dependency on the generator would make "generated by us" a precondition for
 * "renderable by us", and #985 is explicit that any conforming 3.0 or 3.1 document renders here.
 *
 * Everything below is data, so everything below is a class (`CLAUDE.md` §1).
 */

/** One entry of the document's `servers[]`. The first one is what the code samples call. */
export class ServerInfo {
    constructor(
        readonly url: string,
        readonly description: string | undefined,
    ) {}
}

/**
 * One published security scheme. Only the fields a partner has to ACT on are carried: what to send
 * and where. `headerName` is empty for a scheme that is not sent in a header, and the code samples
 * then omit it rather than inventing a header name the server never reads.
 */
export class SecuritySchemeInfo {
    constructor(
        readonly key: string,
        readonly kind: string,
        readonly sentIn: string,
        readonly headerName: string,
        readonly description: string | undefined,
    ) {}
}

/** One response of one operation. */
export class ResponseInfo {
    constructor(
        readonly status: string,
        readonly description: string,
        readonly schema: JsonNode | undefined,
    ) {}
}

/**
 * One rendered page's worth of operation.
 *
 * A WEBHOOK carries `isWebhook`, and with it no method, no path and no code samples. The url belongs
 * to the PARTNER, so a curl of ours against one would invite them to call something that does not
 * exist — see `responsibilities.md`.
 */
export class OperationInfo {
    constructor(
        readonly name: string,
        readonly slug: string,
        readonly httpMethod: string,
        readonly path: string,
        readonly description: string,
        readonly tag: string,
        readonly requestSchema: JsonNode | undefined,
        readonly responses: readonly ResponseInfo[],
        readonly isWebhook: boolean,
        readonly securityKeys: readonly string[],
        /**
         * The event NAME a webhook is keyed by in the document's `webhooks:` block, and the empty
         * string for an ordinary operation. It is carried separately from `name` because the two
         * are different published facts — `orderStateChanged` is what we call the method,
         * `order.state-changed` is what the partner matches on the wire.
         */
        readonly eventName: string,
    ) {}
}

/**
 * One nav section: an OpenAPI tag and the operations under it, webhooks appended after the
 * operations that share the tag. EVERY tag gets one — a tag missing from the sidebar is an operation
 * a partner cannot find, which reads exactly like an operation that does not exist.
 */
export class TagSection {
    constructor(
        readonly name: string,
        readonly description: string,
        readonly operations: readonly OperationInfo[],
    ) {}
}

/**
 * One named schema from `components.schemas`.
 *
 * `hasOwnPage` is true for an OBJECT only. A named enum or scalar alias stays inline at every use
 * site, because a page carrying one line of chips is a click that costs the reader the context they
 * were reading in.
 */
export class NamedSchema {
    constructor(
        readonly name: string,
        readonly slug: string,
        readonly node: JsonNode,
        readonly hasOwnPage: boolean,
    ) {}
}

/** The whole document, read once. */
export class ApiSpec {
    constructor(
        readonly title: string,
        readonly version: string,
        readonly description: string,
        readonly servers: readonly ServerInfo[],
        readonly sections: readonly TagSection[],
        readonly securitySchemes: readonly SecuritySchemeInfo[],
        readonly schemas: readonly NamedSchema[],
        readonly documentSecurityKeys: readonly string[],
    ) {}

    /** The named schema `name` refers to, or `undefined` when the document does not define it. */
    schemaNamed(name: string): NamedSchema | undefined {
        return this.schemas.find((schema: NamedSchema): boolean => schema.name === name);
    }

    /** Every operation, across every section, in published order. */
    operations(): readonly OperationInfo[] {
        const all: OperationInfo[] = [];
        for (const section of this.sections) {
            all.push(...section.operations);
        }
        return all;
    }
}
