/** Everything an OpenAPI document can hold. It is JSON, so this is the whole value space. */
export type JsonValue = string | number | boolean | null | JsonValue[] | JsonMap;

/** The object case of {@link JsonValue}, named so the recursive alias can refer to it. */
export type JsonMap = { [key: string]: JsonValue };

/**
 * A READER over one JSON value, and the reason this package can render a document it did not
 * generate.
 *
 * The alternative — importing `@webpieces/openapi-generator`'s document classes, which are
 * structurally identical — would make "generated by us" a precondition for "renderable by us"
 * (issue #985). So the document is read STRUCTURALLY: every accessor asks "is there a string at this
 * key", never "is this an instance of our class", and a key that is absent or the wrong shape comes
 * back `undefined` instead of throwing. A conforming document written by any other tool reads the
 * same way.
 *
 * It is deliberately total rather than validating. A docs site that refuses to render because one
 * optional `description` was a number is worse than one that renders the rest: the reader loses a
 * whole reference over a field they were not looking at.
 */
export class JsonNode {
    // webpieces-disable no-any-unknown -- the document is FOREIGN input; narrowing it is this class's whole job
    constructor(readonly raw: unknown) {}

    /** True when this node is a JSON object (and not an array, and not null). */
    isObject(): boolean {
        return typeof this.raw === 'object' && this.raw !== null && !Array.isArray(this.raw);
    }

    /** The keys of this object, in document order. Empty for anything that is not an object. */
    keys(): readonly string[] {
        if (!this.isObject()) {
            return [];
        }
        return Object.keys(this.raw as JsonMap);
    }

    /** The child at `key`, always a node — an absent key reads as a node over `undefined`. */
    at(key: string): JsonNode {
        if (!this.isObject()) {
            return new JsonNode(undefined);
        }
        return new JsonNode((this.raw as JsonMap)[key]);
    }

    /** The string at `key`, or `undefined` when it is absent or is not a string. */
    text(key: string): string | undefined {
        const value = this.at(key).raw;
        return typeof value === 'string' ? value : undefined;
    }

    /** This node itself as a string, or `undefined`. */
    asText(): string | undefined {
        return typeof this.raw === 'string' ? this.raw : undefined;
    }

    /** The boolean at `key`, or `undefined`. A missing flag is not `false`; the caller decides. */
    flag(key: string): boolean | undefined {
        const value = this.at(key).raw;
        return typeof value === 'boolean' ? value : undefined;
    }

    /** The number at `key`, or `undefined`. */
    number(key: string): number | undefined {
        const value = this.at(key).raw;
        return typeof value === 'number' ? value : undefined;
    }

    /** The array at `key` as nodes. Empty when absent or not an array. */
    list(key: string): readonly JsonNode[] {
        return this.at(key).asList();
    }

    /** This node itself as an array of nodes. Empty when it is not an array. */
    asList(): readonly JsonNode[] {
        if (!Array.isArray(this.raw)) {
            return [];
        }
        return (this.raw as JsonValue[]).map((entry: JsonValue): JsonNode => new JsonNode(entry));
    }

    /** Every own entry of this object as `[key, node]`, in document order. */
    entries(): readonly JsonEntry[] {
        return this.keys().map((key: string): JsonEntry => new JsonEntry(key, this.at(key)));
    }

    /** True when this node holds nothing at all — an absent key, or an explicit `null`. */
    isAbsent(): boolean {
        return this.raw === undefined || this.raw === null;
    }
}

/** One `[key, value]` pair of a JSON object, as a class because it is data. */
export class JsonEntry {
    constructor(
        readonly key: string,
        readonly value: JsonNode,
    ) {}
}
