import { RetiredConfigKey } from '@webpieces/rules-sdk';

/** Rejected obsolete workflow switches, preserving their exact repair instructions. */
export const ruleMigrations: readonly RetiredConfigKey[] = [
    new RetiredConfigKey("rule", "pr-merge-cleanup", "pr-lifecycle-guard", "Rename the key to \"pr-lifecycle-guard\" (merging its value into that entry if you already have one — the four PR/merge guards share one key now). Its mode and escape hatches carry over.", "[pr-merge-cleanup]", false),
    new RetiredConfigKey("rule", "pr-creation-guard", "pr-lifecycle-guard", "Rename the key to \"pr-lifecycle-guard\" (merging its value into that entry if you already have one — the four PR/merge guards share one key now). Its mode and escape hatches carry over; the old \"upsertPrCommand\" field does NOT — that string lives only in commands.guardHints.prCreationOrPush.", "[pr-creation-guard]", false),
    new RetiredConfigKey("rule", "main-stale-guard", "branch-state-guard", "Rename the key to \"branch-state-guard\" (merging its value into that entry if you already have one — the four branch-state guards share one key now). Its mode and escape hatches carry over. Note the widened scope: that key arms the Write, Read AND Bash halves of the branch-state policy, not just the Read block this key used to name.", "[main-stale-guard]", false),
    new RetiredConfigKey("rule", "whole-repo-build-guard", "~/.webpieces/config.json → experimental.whole-repo-build-guard", "DELETE this entry from webpieces.config.json — no repo config key controls this guard any more. The guard is OFF by default for everyone, with no file and no key required. To turn it ON for YOUR machine only, put {\"experimental\": {\"whole-repo-build-guard\": true}} in ~/.webpieces/config.json — that file is optional and is tracked by no repo.", "[whole-repo-build-guard]", true),
    new RetiredConfigKey("rule", "feature-branch-guard", "branch-state-guard", "MERGE it into ONE \"branch-state-guard\" entry under \"hookGuards\". All four of feature-branch-guard, read-stale-guard, stale-main-bash-guard and merged-branch-bash-guard now read that single entry — they are one policy (\"may I work here, and is what I read current?\") implemented by four classes, and configuring them separately let you switch on half of it. Keep \"mode\", \"turnOffRuleUntilEpoch\" and \"turnOffRuleWhileOnBranch\"; the ONE \"hangTimeoutMinutes\" survives (there was only ever one refresher and one cache, so at most one of the four values could ever take effect); \"branchNamingConvention\" survives from feature-branch-guard. If the four disagreed on \"mode\", pick the one you meant — \"ON\" arms the whole policy including the Read block. Then DELETE this key.", "[feature-branch-guard]", false),
    new RetiredConfigKey("rule", "read-stale-guard", "branch-state-guard", "MERGE it into ONE \"branch-state-guard\" entry under \"hookGuards\". All four of feature-branch-guard, read-stale-guard, stale-main-bash-guard and merged-branch-bash-guard now read that single entry — they are one policy (\"may I work here, and is what I read current?\") implemented by four classes, and configuring them separately let you switch on half of it. Keep \"mode\", \"turnOffRuleUntilEpoch\" and \"turnOffRuleWhileOnBranch\"; the ONE \"hangTimeoutMinutes\" survives (there was only ever one refresher and one cache, so at most one of the four values could ever take effect); \"branchNamingConvention\" survives from feature-branch-guard. If the four disagreed on \"mode\", pick the one you meant — \"ON\" arms the whole policy including the Read block. Then DELETE this key.", "[read-stale-guard]", false),
    new RetiredConfigKey("rule", "stale-main-bash-guard", "branch-state-guard", "MERGE it into ONE \"branch-state-guard\" entry under \"hookGuards\". All four of feature-branch-guard, read-stale-guard, stale-main-bash-guard and merged-branch-bash-guard now read that single entry — they are one policy (\"may I work here, and is what I read current?\") implemented by four classes, and configuring them separately let you switch on half of it. Keep \"mode\", \"turnOffRuleUntilEpoch\" and \"turnOffRuleWhileOnBranch\"; the ONE \"hangTimeoutMinutes\" survives (there was only ever one refresher and one cache, so at most one of the four values could ever take effect); \"branchNamingConvention\" survives from feature-branch-guard. If the four disagreed on \"mode\", pick the one you meant — \"ON\" arms the whole policy including the Read block. Then DELETE this key.", "[stale-main-bash-guard]", false),
    new RetiredConfigKey("rule", "merged-branch-bash-guard", "branch-state-guard", "MERGE it into ONE \"branch-state-guard\" entry under \"hookGuards\". All four of feature-branch-guard, read-stale-guard, stale-main-bash-guard and merged-branch-bash-guard now read that single entry — they are one policy (\"may I work here, and is what I read current?\") implemented by four classes, and configuring them separately let you switch on half of it. Keep \"mode\", \"turnOffRuleUntilEpoch\" and \"turnOffRuleWhileOnBranch\"; the ONE \"hangTimeoutMinutes\" survives (there was only ever one refresher and one cache, so at most one of the four values could ever take effect); \"branchNamingConvention\" survives from feature-branch-guard. If the four disagreed on \"mode\", pick the one you meant — \"ON\" arms the whole policy including the Read block. Then DELETE this key.", "[merged-branch-bash-guard]", false),
    new RetiredConfigKey("rule", "pr-creation-or-push-guard", "pr-lifecycle-guard", "MERGE it into ONE \"pr-lifecycle-guard\" entry under \"hookGuards\". All four of pr-creation-or-push-guard, merge-in-progress-guard, pr-merge-guard and redirect-how-to-merge-main now read that single entry — they are one policy (\"do PRs and merges go through the gated flow?\"). Keep \"mode\", \"turnOffRuleUntilEpoch\" and \"turnOffRuleWhileOnBranch\". Know what \"mode\": \"OFF\" now means: it releases the unvalidated-merge gate as well as the PR/push blocks, because merge-in-progress-guard is under this key too. The per-guard \"upsertPrCommand\" / \"mergeCompleteCommand\" fields are gone — those strings live ONLY in commands.guardHints.prCreationOrPush / .mergeInProgress. Then DELETE this key.", "[pr-creation-or-push-guard]", false),
    new RetiredConfigKey("rule", "merge-in-progress-guard", "pr-lifecycle-guard", "MERGE it into ONE \"pr-lifecycle-guard\" entry under \"hookGuards\". All four of pr-creation-or-push-guard, merge-in-progress-guard, pr-merge-guard and redirect-how-to-merge-main now read that single entry — they are one policy (\"do PRs and merges go through the gated flow?\"). Keep \"mode\", \"turnOffRuleUntilEpoch\" and \"turnOffRuleWhileOnBranch\". Know what \"mode\": \"OFF\" now means: it releases the unvalidated-merge gate as well as the PR/push blocks, because merge-in-progress-guard is under this key too. The per-guard \"upsertPrCommand\" / \"mergeCompleteCommand\" fields are gone — those strings live ONLY in commands.guardHints.prCreationOrPush / .mergeInProgress. Then DELETE this key.", "[merge-in-progress-guard]", false),
    new RetiredConfigKey("rule", "pr-merge-guard", "pr-lifecycle-guard", "MERGE it into ONE \"pr-lifecycle-guard\" entry under \"hookGuards\". All four of pr-creation-or-push-guard, merge-in-progress-guard, pr-merge-guard and redirect-how-to-merge-main now read that single entry — they are one policy (\"do PRs and merges go through the gated flow?\"). Keep \"mode\", \"turnOffRuleUntilEpoch\" and \"turnOffRuleWhileOnBranch\". Know what \"mode\": \"OFF\" now means: it releases the unvalidated-merge gate as well as the PR/push blocks, because merge-in-progress-guard is under this key too. The per-guard \"upsertPrCommand\" / \"mergeCompleteCommand\" fields are gone — those strings live ONLY in commands.guardHints.prCreationOrPush / .mergeInProgress. Then DELETE this key.", "[pr-merge-guard]", false),
    new RetiredConfigKey("rule", "redirect-how-to-merge-main", "pr-lifecycle-guard", "MERGE it into ONE \"pr-lifecycle-guard\" entry under \"hookGuards\". All four of pr-creation-or-push-guard, merge-in-progress-guard, pr-merge-guard and redirect-how-to-merge-main now read that single entry — they are one policy (\"do PRs and merges go through the gated flow?\"). Keep \"mode\", \"turnOffRuleUntilEpoch\" and \"turnOffRuleWhileOnBranch\". Know what \"mode\": \"OFF\" now means: it releases the unvalidated-merge gate as well as the PR/push blocks, because merge-in-progress-guard is under this key too. The per-guard \"upsertPrCommand\" / \"mergeCompleteCommand\" fields are gone — those strings live ONLY in commands.guardHints.prCreationOrPush / .mergeInProgress. Then DELETE this key.", "[redirect-how-to-merge-main]", false),
    new RetiredConfigKey("field", "pr-lifecycle-guard.upsertPrCommand", "", "This field was removed. The command the push/PR-creation block prints lives in ONE place: \"commands\": { \"guardHints\": { \"prCreationOrPush\": <value> } }. Move your value there and delete this key.", "[pr-lifecycle-guard]", false),
    new RetiredConfigKey("field", "pr-lifecycle-guard.mergeCompleteCommand", "", "This field was removed. The command the unfinished-merge block prints lives in ONE place: \"commands\": { \"guardHints\": { \"mergeInProgress\": <value> } }. Move your value there and delete this key.", "[pr-lifecycle-guard]", false),
];
