/**
 * Mermaid Emitter
 *
 * Renders the DI graph as design.md — a Mermaid `graph TD` diagram that GitHub
 * and IDEs render inline, so the DI design is reviewable in every PR. Emitted
 * in the same sorted order as design.json so diffs are equally stable.
 */

import { DiDesign, DiGraph, DiNode } from './model';
import { sortGraph } from './serializer';

/** Mermaid node ids must be simple identifiers — map graph ids to safe ids. */
function mermaidId(id: string): string {
    return id.replace(/[^A-Za-z0-9_]/g, '_');
}

/** Escape text destined for a quoted mermaid label. */
function label(text: string): string {
    return text.replace(/"/g, '#quot;');
}

/** Escape an edge label (rendered between pipes). */
function edgeLabel(text: string): string {
    return text.replace(/\|/g, '/').replace(/"/g, "'");
}

function nodeStatement(node: DiNode): string {
    const id = mermaidId(node.id);
    const text = label(node.className);
    if (node.kind === 'controller') return `    ${id}["${text}"]:::controller`;
    if (node.kind === 'constant' || node.kind === 'dynamic') return `    ${id}(["${text}"])`;
    if (node.kind === 'unresolved') return `    ${id}{{"${text} ?"}}:::unresolved`;
    return `    ${id}["${text}"]`;
}

function graphBody(design: DiDesign): string[] {
    const lines: string[] = ['graph TD'];
    for (const node of design.nodes) {
        lines.push(nodeStatement(node));
    }
    for (const edge of design.edges) {
        const from = mermaidId(edge.from);
        const to = mermaidId(edge.to);
        const token = edge.injection === 'multiInject' ? `multiInject ${edge.token}` : edge.token;
        if (token !== '') {
            lines.push(`    ${from} -->|${edgeLabel(token)}| ${to}`);
        } else {
            lines.push(`    ${from} --> ${to}`);
        }
    }
    lines.push('    classDef controller fill:#1f6feb,color:#ffffff,stroke:#0d419d');
    lines.push('    classDef unresolved fill:#f0ad4e,color:#000000,stroke:#b8860b,stroke-dasharray: 5 5');
    return lines;
}

/** One `## Root` section with the design's Mermaid diagram. */
function designSection(design: DiDesign): string[] {
    const kind = design.rootKind === 'controller' ? 'controller' : 'root';
    const heading = `## ${design.root} — ${kind}, Level 0…${design.maxLevel}`;
    return [heading, '', '```mermaid', ...graphBody(design), '```', ''];
}

/**
 * Render the design.md content for a project's DI graph — one Mermaid diagram
 * per design (per controller, or per library top-of-DAG root), each rooted at
 * Level 0 with its injections fanning downward.
 */
export function toDesignMarkdown(graph: DiGraph): string {
    sortGraph(graph);

    const header = [
        `# DI Design Graph — ${graph.project}`,
        '',
        `> GENERATED by \`nx run ${graph.project}:di-graph-generate\` — do not edit by hand.`,
        `> Machine-readable version: [design.json](./design.json)`,
        '',
        `Each section below is one root's dependency tree: Level 0 is the root`,
        `(a \`@Controller\` or top-of-DAG class), and constructor injections fan`,
        `downward through Levels 1, 2, … A dependency shared by multiple roots`,
        `appears in each root's tree.`,
        '',
    ];

    if (graph.designs.length === 0) {
        return header.concat(['No DI-registered classes found in this project.', '']).join('\n');
    }

    const sections: string[] = [];
    for (const design of graph.designs) {
        sections.push(...designSection(design));
    }

    const legend = [
        '',
        'Edges are constructor injections: `-->|TOKEN|` for `@inject`/`@multiInject`,',
        'unlabeled arrows for inject-by-type. Rounded nodes are `toConstantValue`/',
        '`toDynamicValue` leaves; dashed nodes are tokens the analyzer could not resolve.',
        '',
    ];

    return header.concat(sections).concat(legend).join('\n');
}
