/**
 * Mermaid Emitter
 *
 * Renders the DI graph as design.md — a Mermaid `graph TD` diagram that GitHub
 * and IDEs render inline, so the DI design is reviewable in every PR. Emitted
 * in the same sorted order as design.json so diffs are equally stable.
 */

import { DiGraph, DiNode } from './model';
import { sortGraph } from './serializer';

/** Mermaid node ids must be simple identifiers — map graph ids to safe ids. */
function mermaidId(id: string): string {
    return id.replace(/[^A-Za-z0-9_]/g, '_');
}

/** Escape text destined for a quoted mermaid label. */
function label(text: string): string {
    return text.replace(/"/g, '#quot;');
}

/** Escape an edge label (rendered between pipes). */
function edgeLabel(text: string): string {
    return text.replace(/\|/g, '/').replace(/"/g, "'");
}

function nodeStatement(node: DiNode): string {
    const id = mermaidId(node.id);
    const text = label(node.className);
    if (node.kind === 'controller') return `    ${id}["${text}"]:::controller`;
    if (node.kind === 'constant' || node.kind === 'dynamic') return `    ${id}(["${text}"])`;
    if (node.kind === 'unresolved') return `    ${id}{{"${text} ?"}}:::unresolved`;
    return `    ${id}["${text}"]`;
}

function graphBody(graph: DiGraph): string[] {
    const lines: string[] = ['graph TD'];
    for (const node of graph.nodes) {
        lines.push(nodeStatement(node));
    }
    for (const edge of graph.edges) {
        const from = mermaidId(edge.from);
        const to = mermaidId(edge.to);
        const token = edge.injection === 'multiInject' ? `multiInject ${edge.token}` : edge.token;
        if (token !== '') {
            lines.push(`    ${from} -->|${edgeLabel(token)}| ${to}`);
        } else {
            lines.push(`    ${from} --> ${to}`);
        }
    }
    lines.push('    classDef controller fill:#1f6feb,color:#ffffff,stroke:#0d419d');
    lines.push('    classDef unresolved fill:#f0ad4e,color:#000000,stroke:#b8860b,stroke-dasharray: 5 5');
    return lines;
}

/**
 * Render the design.md content for a project's DI graph.
 */
export function toDesignMarkdown(graph: DiGraph): string {
    sortGraph(graph);

    const header = [
        `# DI Design Graph — ${graph.project}`,
        '',
        `> GENERATED by \`nx run ${graph.project}:di-graph-generate\` — do not edit by hand.`,
        `> Machine-readable version: [design.json](./design.json)`,
        '',
    ];

    if (graph.nodes.length === 0) {
        return header.concat(['No DI-registered classes found in this project.', '']).join('\n');
    }

    const body = ['```mermaid', ...graphBody(graph), '```', ''];

    const legend = [
        '',
        'Edges are constructor injections: `-->|TOKEN|` for `@inject`/`@multiInject`,',
        'unlabeled arrows for inject-by-type. Rounded nodes are `toConstantValue`/',
        '`toDynamicValue` leaves; dashed nodes are tokens the analyzer could not resolve.',
        '',
    ];

    return header.concat(body).concat(legend).join('\n');
}
