import { ContextKey } from '../ContextKey';

/**
 * Core framework context keys for distributed tracing and request correlation.
 *
 * These are the minimal keys the WebPieces framework needs for:
 * - Request tracking across services (REQUEST_ID -> PREVIOUS_REQUEST_ID chaining per hop)
 * - Request correlation
 * - Log correlation (each key logs under its `name`)
 *
 * Pattern inspired by Java MicroSvcHeader enum. Lives in core-util (browser-safe)
 * so BOTH the http-client (request-id chaining) and http-server can reference it.
 *
 * Exposed as {@link HeaderRegistry.DEFAULT_HEADERS} — a service opts into these by
 * passing `platformHeaders=true` to `HeaderRegistry.configure(...)`.
 *
 * Each key's `name` is the logical/log name; `httpHeader` is the wire name.
 */
export class WebpiecesCoreHeaders {
    /**
     * Unique ID for this request. Generated by the server if not provided.
     * Transferred (propagates downstream) and logged under 'requestId'.
     */
    static readonly REQUEST_ID = new ContextKey('requestId', 'x-request-id');

    /**
     * ID of the previous request in the call chain. When service A calls B, B
     * receives A's REQUEST_ID as PREVIOUS_REQUEST_ID (builds the trace tree).
     */
    static readonly PREVIOUS_REQUEST_ID = new ContextKey('previousId', 'x-previous-request-id');

    /**
     * Correlation ID spanning multiple related requests. Set by the gateway or
     * first service; all hops in the chain share it.
     */
    static readonly CORRELATION_ID = new ContextKey('correlationId', 'x-correlation-id');

    /**
     * Turns on test-case recording for this request (Java: x-webpieces-recording).
     * Transferred so recording follows the request across service hops.
     */
    static readonly RECORDING = new ContextKey('recording', 'x-webpieces-recording');

    /**
     * The bearer credential for an authenticated request (user JWT or service OIDC
     * token). Transferred and SECURED — masked in logs.
     */
    static readonly AUTHORIZATION = new ContextKey('authorization', 'authorization', /*isSecured*/ true);

    /**
     * Shared-secret credential for internal callers that cannot mint OIDC tokens.
     * Transferred and SECURED — masked in logs.
     */
    static readonly SHARED_SECRET = new ContextKey('sharedSecret', 'x-webpieces-shared-secret', /*isSecured*/ true);

    /**
     * Get all core context keys as an array (the platform DEFAULT_HEADERS set).
     */
    static getAllHeaders(): ContextKey[] {
        return [
            WebpiecesCoreHeaders.REQUEST_ID,
            WebpiecesCoreHeaders.PREVIOUS_REQUEST_ID,
            WebpiecesCoreHeaders.CORRELATION_ID,
            WebpiecesCoreHeaders.RECORDING,
            WebpiecesCoreHeaders.AUTHORIZATION,
            WebpiecesCoreHeaders.SHARED_SECRET,
        ];
    }
}
