import { ContextKey } from '../ContextKey';

/**
 * Core framework context keys — the minimum the WebPieces framework needs to correlate one
 * request across every service it touches, and across every log line each of them writes.
 *
 * ONE id, propagated unchanged. The first service to see a request without an `x-request-id`
 * generates one (RequestContextHeaders.fillFromRequest); every hop copies it onward verbatim. Grep that id and you
 * have the whole call tree. There is no per-hop id and no parent pointer: a chain of ids you must
 * stitch back together buys nothing a single shared id does not already give you.
 *
 * Lives in core-util (browser-safe) so both the http clients and http-server can reference it.
 *
 * Exposed as {@link HeaderRegistry.DEFAULT_HEADERS} — a service opts into these by
 * passing `platformHeaders=true` to `HeaderRegistry.configure(...)`.
 *
 * Each key's `name` is the logical/log name; `httpHeader` is the wire name.
 */
export class WebpiecesCoreHeaders {
    /**
     * The id that correlates every hop of one request, and every log line of every hop.
     * Generated by the first service to see a request without one; propagated unchanged after that.
     */
    static readonly REQUEST_ID = new ContextKey('requestId', 'x-request-id');

    static readonly ORG_ID = new ContextKey('orgId', 'x-org-id');

    static readonly USER_ID = new ContextKey('userId', 'x-user-id');

    static readonly USER_ROLES = new ContextKey('roles', 'x-webpieces-roles');

    /**
     * Turns on test-case recording for this request (Java: x-webpieces-recording).
     * Transferred so recording follows the request across service hops.
     */
    static readonly RECORDING = new ContextKey('recording', 'x-webpieces-recording');

    /**
     * NO CREDENTIAL KEYS LIVE HERE.
     *
     * `authorization` and `x-webpieces-shared-secret` used to be ContextKeys. That made them
     * TRANSFERRED keys, so the inbound transfer copied them off the request into the
     * RequestContext, and every outbound RPC call and enqueued Cloud Task then carried the
     * caller's credential onward — to services that had no business seeing it.
     *
     * A credential belongs to ONE request hop. It is read straight off the {@link HttpRequest}
     * by the framework AuthFilter, and written straight onto the outbound request by the client
     * that mints it (NodeProxyClient, GcpTaskInvoker, InMemoryTaskInvoker). It never enters the
     * magic context, so nothing can propagate it by accident.
     *
     * An app that genuinely wants a credential to travel can still register its own ContextKey for
     * it — but that is now an explicit, visible decision rather than the default.
     */

    /**
     * Get all core context keys as an array (the platform DEFAULT_HEADERS set).
     */
    static getAllHeaders(): ContextKey[] {
        return [
            WebpiecesCoreHeaders.REQUEST_ID,
            WebpiecesCoreHeaders.USER_ID,
            WebpiecesCoreHeaders.ORG_ID,
            WebpiecesCoreHeaders.USER_ROLES,
            WebpiecesCoreHeaders.RECORDING,
        ];
    }
}
