import { ContextKey } from '../ContextKey';

/**
 * Core framework context keys — the minimum the WebPieces framework needs to correlate one
 * request across every service it touches, and across every log line each of them writes.
 *
 * ONE id, propagated unchanged. The first service to see a request without an `x-request-id`
 * generates one (RequestContextHeaders.fillFromRequest); every hop copies it onward verbatim. Grep that id and you
 * have the whole call tree. There is no per-hop id and no parent pointer: a chain of ids you must
 * stitch back together buys nothing a single shared id does not already give you.
 *
 * Lives in core-util (browser-safe) so both the http clients and http-server can reference it.
 *
 * Exposed as {@link HeaderRegistry.DEFAULT_HEADERS} — a service opts into these by
 * passing `platformHeaders=true` to `HeaderRegistry.configure(...)`.
 *
 * Each key's `name` is the logical/log name; `httpHeader` is the wire name.
 */
export class WebpiecesCoreHeaders {
    /**
     * The id that correlates every hop of one request, and every log line of every hop.
     * Generated by the first service to see a request without one; propagated unchanged after that.
     */
    static readonly REQUEST_ID = new ContextKey('requestId', 'x-request-id');

    /**
     * WHICH SERVICE MINTED {@link REQUEST_ID} — the name from {@link ServiceInfo}, stamped by
     * `RequestContextHeaders.fillFromRequest` ONLY on the branch that generates a new id (i.e. when
     * the inbound request carried no `x-request-id`). It answers the question the id alone cannot:
     * "this trace starts here — is that right?" An id appearing with no source means it came from
     * outside; an id sourced by a service that should never be an entry point is a routing bug.
     *
     * - `httpHeader` UNDEFINED → NOT transferred over the wire, and that is the WHOLE POINT. If it
     *   travelled, hop 2 would inherit it, hop 3 would inherit it, and "who started this trace"
     *   would be indistinguishable from "who passed it along" — the origin, the one fact this key
     *   carries, would be lost. It is absent on every hop that did NOT mint the id, which is exactly
     *   the signal: present == I am the origin.
     * - `isLogged` TRUE → emitted as a plain string at `jsonPayload.requestIdSource`.
     */
    static readonly REQUEST_ID_SOURCE = new ContextKey(
        'requestIdSource',
        /*httpHeader*/ undefined
    );

    /**
     * The CALLER's build version — so a downstream server's logs record which build of the client
     * called it (surfaces as `jsonPayload.clientVersion`). Distinct from the log line's own `version`
     * (this service's build): `version` answers "which build wrote this line?", `clientVersion`
     * answers "which build asked us to?".
     *
     * - `httpHeader` SET → transferred over the wire, BUT unlike a normal transferred key it is NOT
     *   copied from the context onward. Each hop OVERWRITES it with its OWN `ServiceInfo.getVersion()`
     *   as it becomes the client to the next hop (see `buildOutboundHeaders`), so on any given server
     *   `clientVersion` is always the IMMEDIATE caller's version, never a stale grand-caller's.
     * - `isLogged` TRUE → the inbound value lands in the context and flows through the normal log
     *   field map; no backend change needed.
     */
    static readonly CLIENT_VERSION = new ContextKey('clientVersion', 'x-webpieces-client-version');

    /**
     * A frontend/app-minted correlation id that groups every request triggered by ONE user ACTION.
     *
     * An "action" is a single thing the user did in the GUI — a CLICK on a button/link, or TYPING in a
     * field — or a background poller tick: anything that may fan out into MULTIPLE remote calls. That one
     * action fires 1..N browser HTTP calls, each of which gets its own framework-minted {@link REQUEST_ID}
     * (one per HTTP call, shared within that call's server→server subtree). `actionId` sits ABOVE
     * `requestId` and is what stitches those N requests back to the single action that caused them:
     *
     *     actionId  (app-minted, ONE per user action, rides EVERY call of that action)
     *        └── 1..N requestId  (framework-minted, ONE per HTTP call)
     *
     * Grep one `actionId` in the logs → every `requestId` it spawned, and every log line of the whole
     * action. Minted and refreshed by the app (a UI concern), carried under `x-webpieces-actionid`.
     *
     * Browser/app-minted ONLY: unlike {@link REQUEST_ID}, the framework transfers and logs it but must
     * NOT auto-mint one server-side. Absent `actionId` ⇒ a non-action flow (system / cron / task), which
     * is the correct signal.
     *
     * - `httpHeader` SET → transferred: copied off the inbound request into context and re-emitted on
     *   outbound hops, so the id follows the action across services.
     * - `isLogged` TRUE → emitted as a plain string on every log line of the request.
     */
    static readonly ACTION_ID = new ContextKey('actionId', 'x-webpieces-actionid');

    static readonly ORG_ID = new ContextKey('orgId', 'x-org-id');

    static readonly USER_ID = new ContextKey('userId', 'x-user-id');

    static readonly USER_ROLES = new ContextKey('roles', 'x-webpieces-roles');

    /**
     * Turns on test-case recording for this request (Java: x-webpieces-recording).
     * Transferred so recording follows the request across service hops.
     */
    static readonly RECORDING = new ContextKey('recording', 'x-webpieces-recording');

    /**
     * The structured API-call tag ({@link ApiCallInfo}) stamped by {@link LogApiCall} around every
     * outbound (client) / inbound (server) call. It rides the magic context so EVERY log line emitted
     * during the call inherits a filterable `api` object, surfacing in GCP as nested
     * `jsonPayload.api.{side,type,result,path,method}`.
     *
     * - `httpHeader` UNDEFINED → NOT transferred over the wire. Per-hop only: each server/client hop
     *   stamps its own tag, so a downstream server records `side:'server'`, never the caller's `side:'client'`.
     * - `isLogged` TRUE → emitted by the logging backends. It carries an OBJECT value, so the backends
     *   read it via {@link HeaderRegistry.buildStructuredLogFields} (object-aware); the flat
     *   `buildLogFields()` string map deliberately skips it (typeof-string guard).
     */
    static readonly API_CALL_INFO = new ContextKey('api', /*httpHeader*/ undefined, /*isSecured*/ false, /*isLogged*/ true);

    /**
     * The inbound request's HTTP method and path, stamped ONCE from the {@link HttpRequest} by
     * `RequestContextHeaders.fillFromRequest` (the atomic inbound choke point every transport funnels
     * through). They surface as top-level `jsonPayload.httpMethod` / `jsonPayload.requestPath` so every
     * log line of the request carries them — they used to ride inside {@link ApiCallInfo} (`api.path` /
     * `api.method`) but that coupled a per-CALL logger to the per-REQUEST transport shape.
     *
     * - `httpHeader` UNDEFINED → NOT transferred over the wire: a downstream hop stamps its OWN inbound
     *   method/path, never the caller's. Outbound client calls never set these (no inbound path).
     * - `isLogged` TRUE → emitted by the logging backends as plain strings.
     */
    static readonly HTTP_METHOD = new ContextKey('httpMethod', /*httpHeader*/ undefined, /*isSecured*/ false, /*isLogged*/ true);

    static readonly REQUEST_PATH = new ContextKey('requestPath', /*httpHeader*/ undefined, /*isSecured*/ false, /*isLogged*/ true);

    /**
     * The routed endpoint's IMPLEMENTATION identity: the concrete controller class name
     * ({@link RouteMetadata.controllerClassName}, e.g. `LoginController`) and the handler method NAME
     * ({@link RouteMetadata.methodName}, e.g. `login`), stamped once per request by {@link LogApiFilter}
     * after route matching so every subsequent log line of the request carries them.
     *
     * These say WHICH CODE ran, which is what you actually grep for — far more useful than the raw
     * `requestPath`. They are the top-level, filterable twin of what previously only lived nested in
     * {@link ApiCallInfo} (`api.method.controllerName` / `api.method.methodName`). The local console
     * formatters render them together as a compact `[Controller.method]` bracket; GCP keeps them as two
     * separate `jsonPayload.controller` / `jsonPayload.method` fields.
     *
     * NOTE: `method` here is the CODE method name (e.g. `login`), NOT the HTTP verb — that is
     * {@link HTTP_METHOD} (`httpMethod`).
     *
     * - `httpHeader` UNDEFINED → NOT transferred: each hop stamps its OWN routed controller/method.
     * - `isLogged` TRUE → emitted by the logging backends as plain strings.
     */
    static readonly CONTROLLER = new ContextKey('controller', /*httpHeader*/ undefined, /*isSecured*/ false, /*isLogged*/ true);

    static readonly METHOD = new ContextKey('method', /*httpHeader*/ undefined, /*isSecured*/ false, /*isLogged*/ true);

    /**
     * NO CREDENTIAL KEYS LIVE HERE.
     *
     * `authorization` and `x-webpieces-shared-secret` used to be ContextKeys. That made them
     * TRANSFERRED keys, so the inbound transfer copied them off the request into the
     * RequestContext, and every outbound RPC call and enqueued Cloud Task then carried the
     * caller's credential onward — to services that had no business seeing it.
     *
     * A credential belongs to ONE request hop. It is read straight off the {@link HttpRequest}
     * by the framework AuthFilter, and written straight onto the outbound request by the client
     * that mints it (NodeProxyClient, GcpTaskInvoker, InMemoryTaskInvoker). It never enters the
     * magic context, so nothing can propagate it by accident.
     *
     * An app that genuinely wants a credential to travel can still register its own ContextKey for
     * it — but that is now an explicit, visible decision rather than the default.
     */

    /**
     * Get all core context keys as an array (the platform DEFAULT_HEADERS set).
     */
    static getAllHeaders(): ContextKey[] {
        return [
            WebpiecesCoreHeaders.REQUEST_ID,
            WebpiecesCoreHeaders.REQUEST_ID_SOURCE,
            WebpiecesCoreHeaders.CLIENT_VERSION,
            WebpiecesCoreHeaders.ACTION_ID,
            WebpiecesCoreHeaders.USER_ID,
            WebpiecesCoreHeaders.ORG_ID,
            WebpiecesCoreHeaders.USER_ROLES,
            WebpiecesCoreHeaders.RECORDING,
            WebpiecesCoreHeaders.API_CALL_INFO,
            WebpiecesCoreHeaders.HTTP_METHOD,
            WebpiecesCoreHeaders.REQUEST_PATH,
            WebpiecesCoreHeaders.CONTROLLER,
            WebpiecesCoreHeaders.METHOD,
        ];
    }
}
