#!/usr/bin/env node
import { execSync, spawnSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { WEBPIECES_TMP_DIR, MERGE_EXPLANATION_FILE } from '@webpieces/rules-config';
import { getFeatureName } from './workflow/git-readAiBranchName';
import { main as gatherInfo } from './git-gatherInfo';
import { main as cleanTmp } from './workflow/cleanTmp';
import { runGitChecked } from './workflow/git-exec';
import {
    MergeMarker,
    mergeDirFor,
    perFileContextDir,
    readMergeMarker,
    writeMergeMarker,
    clearMergeMarker,
} from './workflow/merge-state';

const SEP = '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n';

interface HashPoints {
    hashForkPoint: string;
    hashFeatureHead: string;
    hashMainHead: string;
}

function detectPr(currentBranch: string): string {
    const result = spawnSync(
        'gh', ['pr', 'list', '--head', currentBranch, '--json', 'number', '--jq', '.[0].number'],
        { encoding: 'utf8' },
    );
    return result.status === 0 ? (result.stdout ?? '').trim() : '';
}

function createBackup(currentBranch: string): string {
    process.stdout.write('\n' + SEP + '💾 Creating Incremental Backup\n' + SEP + '\n');
    let n = 1;
    while (spawnSync('git', ['show-ref', '--verify', '--quiet', `refs/heads/${currentBranch}Backup${n}`]).status === 0) {
        n += 1;
    }
    const backupBranch = `${currentBranch}Backup${n}`;
    runGitChecked(['checkout', '-b', backupBranch], 'Failed to create backup branch');
    runGitChecked(['checkout', currentBranch], 'Failed to return to feature branch');
    process.stdout.write(`✅ Backup created: ${backupBranch}\n\n`);
    return backupBranch;
}

function saveConflictContext(
    conflictedFiles: string[], mergeDir: string, forkPoint: string, featureHead: string, mainHead: string,
): void {
    for (const file of conflictedFiles) {
        const fileDir = perFileContextDir(mergeDir, file);
        fs.mkdirSync(fileDir, { recursive: true });

        const fork = spawnSync('git', ['show', `${forkPoint}:${file}`], { encoding: 'utf8' });
        fs.writeFileSync(path.join(fileDir, 'A-forkpoint.txt'), fork.status === 0 ? (fork.stdout ?? '') : '(file did not exist)\n');
        const feature = spawnSync('git', ['show', `${featureHead}:${file}`], { encoding: 'utf8' });
        fs.writeFileSync(path.join(fileDir, 'B-feature.txt'), feature.status === 0 ? (feature.stdout ?? '') : '(file did not exist)\n');
        const main = spawnSync('git', ['show', `${mainHead}:${file}`], { encoding: 'utf8' });
        fs.writeFileSync(path.join(fileDir, 'C-main.txt'), main.status === 0 ? (main.stdout ?? '') : '(file did not exist)\n');

        const ba = spawnSync('git', ['diff', forkPoint, featureHead, '--', file], { encoding: 'utf8' });
        fs.writeFileSync(path.join(fileDir, 'B-A.diff'), ba.stdout ?? '');
        const ca = spawnSync('git', ['diff', forkPoint, mainHead, '--', file], { encoding: 'utf8' });
        fs.writeFileSync(path.join(fileDir, 'C-A.diff'), ca.stdout ?? '');
    }
}

// Single source of truth for the merge process. The script WRITES it at conflict time (rather
// than the AI relying on a separate hand-maintained doc), parameterized with the live MERGE_DIR
// and conflicted-file list, so the instructions can never drift from the actual layout. The body
// is a template constant with {{...}} placeholders so this stays a small filler function.
const MERGE_PROCESS_TEMPLATE = `# AI-Assisted Squash-Merge Conflict Resolution (generated)

This file was generated by \`pnpm wp-git-update\` when the 3-point squash-merge hit conflicts.
It is the single source of truth for the merge process — follow it exactly.

You are on branch \`{{SQUASH_BRANCH}}\` with conflict markers in the working tree.
\`MERGE_DIR = {{MERGE_DIR}}\`

## How the gate works

- Resolve every conflicted file in the working tree.
- Run **\`pnpm wp-git-merge-complete\`** — the validation gate. It scans for leftover conflict
  markers, checks each conflicted file has a written merge explanation, runs the \`nx affected\`
  build, and — only if all pass — stages, commits, and unblocks the workflow.
- **Do NOT run \`git add\` / \`git commit\` / \`git push\` / \`gh pr\` yourself.** They are blocked by
  the \`merge-in-progress-guard\` hook until the gate validates. The gate does the commit.

## STEP 1 — Load the merge context

Per conflicted file, \`MERGE_DIR/updatemain-<safe_path>/\` holds (\`<safe_path>\` = path with \`/\`→\`__\`):

\`\`\`
A-forkpoint.txt   # file at fork point (base)
B-feature.txt     # file on your feature branch
C-main.txt        # file on main
B-A.diff          # what your feature changed (B−A)
C-A.diff          # what main changed (C−A)
\`\`\`

\`updatemain-hashes.json\` holds A/B/C commit hashes. To see why main changed:
\`git log <A>..<C> --oneline\`.

## STEP 2 — Resolve each conflicted file

For each file: read the working-tree file (the markers) and its \`B-A.diff\` / \`C-A.diff\` (intent),
then Edit to the resolved version, removing ALL conflict markers.

Strategies: goals align & non-overlapping → merge both · one side removes what the other modifies
→ prefer the removal · same lines, simple (imports/format) → merge both · same lines, complex or
conflicting goals → ask the user · feature re-implements what main already squashed → prefer
main's, then re-apply only the genuinely new feature work.

**Then write a merge explanation** for each conflicted file — NOT a comment in the source (that
breaks for JSON and deleted files). Write it next to that file's diffs, at:

\`\`\`
MERGE_DIR/updatemain-<safe_path>/{{EXPLANATION_FILE}}
\`\`\`

(\`<safe_path>\` = the conflict file path with \`/\` → \`__\`, the same dir that holds its
\`A-forkpoint.txt\` / \`B-A.diff\` / \`C-A.diff\`.) In it, explain in a few sentences how you resolved
this file: which side you took where, what you combined from B-A.diff vs C-A.diff, and why. The
gate fails if any conflicted file's explanation is missing or empty. Do not paste A/B/C context
blocks into the source code.

## STEP 3 — Run the gate

\`\`\`
pnpm wp-git-merge-complete
\`\`\`

- Leftover conflict markers → fix those files and re-run.
- Missing merge explanation → write it (see STEP 2) and re-run.
- Build failure → fix the TypeScript/lint errors and re-run (the gate re-stages for you).
- On success it commits and prints the finalize instruction.

## STEP 4 — Finalize

\`\`\`
pnpm wp-upsert-pr      # (or pnpm wp-git-update)
\`\`\`

Force-pushes the resolved squash branch over your feature branch and updates/creates the PR.

## Conflicted files

{{FILE_LIST}}

## If you need to bail out

A backup branch was created (e.g. \`<feature>Backup1\`). To abandon:

\`\`\`
git merge --abort 2>/dev/null; git checkout <feature> ; git branch -D {{SQUASH_BRANCH}}
\`\`\`

Then delete \`{{MERGE_DIR}}/\` for a clean slate.
`;

function mergeProcessDoc(mergeDir: string, squashBranch: string, conflictedFiles: string[]): string {
    const fileList = conflictedFiles.map((f: string): string => `- \`${f}\``).join('\n');
    return MERGE_PROCESS_TEMPLATE
        .replace(/\{\{SQUASH_BRANCH\}\}/g, squashBranch)
        .replace(/\{\{MERGE_DIR\}\}/g, mergeDir)
        .replace(/\{\{EXPLANATION_FILE\}\}/g, MERGE_EXPLANATION_FILE)
        .replace(/\{\{FILE_LIST\}\}/g, fileList);
}

// Returns the absolute path of the written doc.
function writeMergeProcessDoc(repoRoot: string, mergeDir: string, squashBranch: string, conflictedFiles: string[]): string {
    const docDir = path.join(repoRoot, WEBPIECES_TMP_DIR, 'instruct-ai');
    fs.mkdirSync(docDir, { recursive: true });
    const docPath = path.join(docDir, 'webpieces.mergeprocess.md');
    fs.writeFileSync(docPath, mergeProcessDoc(mergeDir, squashBranch, conflictedFiles));
    return docPath;
}

function printConflictHandback(docPath: string, mergeDir: string, squashBranch: string, conflictedFiles: string[]): void {
    process.stdout.write('\n' + SEP + `⚠️  Conflicts in ${conflictedFiles.length} file(s) — handing control back to you\n` + SEP + '\n');
    process.stdout.write(`You are on branch ${squashBranch} with conflicts in the working tree.\n\n`);
    process.stdout.write(`FOLLOW THE MERGE PROCESS:  ${docPath}\n`);
    process.stdout.write(`3-point context per file in: ${mergeDir}/updatemain-<file>/\n\n`);
    process.stdout.write('Conflicted files:\n');
    for (const file of conflictedFiles) process.stdout.write(`  - ${file}\n`);
    process.stdout.write('\n' + SEP);
}

function handleConflictsHandback(
    repoRoot: string, mergeDir: string, currentBranch: string, squashBranch: string,
    backupBranch: string, prNumber: string, hashes: HashPoints,
): void {
    const raw = execSync('git diff --name-only --diff-filter=U', { encoding: 'utf8' }).trim();
    const conflictedFiles = raw.split('\n').filter((f: string): boolean => f.trim() !== '');
    fs.writeFileSync(path.join(mergeDir, 'updatemain-conflicted-files.txt'), raw + '\n');
    saveConflictContext(conflictedFiles, mergeDir, hashes.hashForkPoint, hashes.hashFeatureHead, hashes.hashMainHead);

    const marker = new MergeMarker(
        currentBranch, squashBranch, backupBranch, prNumber, conflictedFiles,
        hashes.hashForkPoint, hashes.hashFeatureHead, hashes.hashMainHead, false,
    );
    writeMergeMarker(mergeDir, marker);
    const docPath = writeMergeProcessDoc(repoRoot, mergeDir, squashBranch, conflictedFiles);
    printConflictHandback(docPath, mergeDir, squashBranch, conflictedFiles);
    process.exit(2);
}

function finalizeBranch(
    currentBranch: string, squashBranch: string, backupBranch: string, prNumber: string,
): void {
    process.stdout.write('\n' + SEP + '🗑️  Finalizing\n' + SEP + '\n');
    runGitChecked(['branch', '-D', currentBranch], 'Failed to delete old feature branch');

    const remoteExists = spawnSync('git', ['ls-remote', '--exit-code', '--heads', 'origin', currentBranch]).status === 0;
    if (remoteExists) {
        process.stdout.write(prNumber ? `Updating PR #${prNumber} (force-with-lease)...\n` : 'Updating remote branch (force-with-lease)...\n');
        runGitChecked(['push', '-u', '--force-with-lease', 'origin', `${squashBranch}:${currentBranch}`], 'Failed to push to origin');
    } else {
        process.stdout.write('No remote branch — local only.\n');
    }
    runGitChecked(['checkout', squashBranch], 'Failed to checkout squash branch');
    runGitChecked(['branch', '-m', currentBranch], 'Failed to rename squash branch');

    process.stdout.write(`\n✅ Branch ${currentBranch} updated from main. Backup: ${backupBranch}\n`);
    process.stdout.write(`   Delete backup when safe: git branch -D ${backupBranch}\n\n`);
}

async function handleResume(mergeDir: string, marker: MergeMarker): Promise<void> {
    if (!marker.validated) {
        process.stdout.write('\n' + SEP + '⏸️  Merge in progress — not yet validated\n' + SEP + '\n');
        process.stdout.write('Resolve the remaining conflicts in the working tree, then run:\n');
        process.stdout.write('  pnpm wp-git-merge-complete\n\n');
        process.exit(1);
    }
    process.stdout.write('Resuming: merge validated — finalizing.\n');
    finalizeBranch(marker.currentBranch, marker.squashBranch, marker.backupBranch, marker.prNumber);
    clearMergeMarker(mergeDir);
    await cleanTmp();
}

async function runFreshUpdate(repoRoot: string, mergeDir: string): Promise<void> {
    const currentBranch = execSync('git branch --show-current', { encoding: 'utf8' }).trim();
    if (currentBranch.endsWith('Squash')) {
        process.stderr.write(`❌ On a leftover ${currentBranch} branch with no merge marker. Clean up: git branch -D ${currentBranch}\n`);
        process.exit(1);
    }

    process.stdout.write('\n' + SEP + '🔄 Squash-Merge Update from Main\n' + SEP + '\n');
    await gatherInfo();
    const hashes = JSON.parse(fs.readFileSync(path.join(mergeDir, 'updatemain-hashes.json'), 'utf8')) as HashPoints;

    const prNumber = detectPr(currentBranch);
    process.stdout.write(prNumber ? `Existing PR #${prNumber} will be updated.\n` : 'No existing PR (one can be created later).\n');

    const backupBranch = createBackup(currentBranch);
    const squashBranch = `${currentBranch}Squash`;
    if (spawnSync('git', ['show-ref', '--verify', '--quiet', `refs/heads/${squashBranch}`]).status === 0) {
        process.stderr.write(`❌ Stale ${squashBranch} from a previous run. Delete it: git branch -D ${squashBranch}\n`);
        process.exit(1);
    }

    runGitChecked(['checkout', 'main'], 'Failed to checkout main');
    runGitChecked(['pull', 'origin', 'main'], 'Failed to pull origin/main');
    runGitChecked(['checkout', '-b', squashBranch], 'Failed to create squash branch');

    process.stdout.write('\n' + SEP + `🔀 Squash merging ${currentBranch}\n` + SEP + '\n');
    const merge = spawnSync('git', ['merge', '--squash', currentBranch], { stdio: 'inherit' });
    if (merge.status !== 0) {
        handleConflictsHandback(repoRoot, mergeDir, currentBranch, squashBranch, backupBranch, prNumber, hashes);
        return;
    }

    const nothingStaged = spawnSync('git', ['diff-index', '--quiet', '--cached', 'HEAD', '--']).status === 0;
    if (nothingStaged) {
        process.stdout.write('ℹ️  Already up-to-date with main (nothing to merge).\n');
    } else {
        runGitChecked(['commit', '-m', `Squash merge of ${currentBranch}`], 'Failed to commit squash merge');
    }
    finalizeBranch(currentBranch, squashBranch, backupBranch, prNumber);
    await cleanTmp();
}

export async function main(): Promise<void> {
    const repoRoot = execSync('git rev-parse --show-toplevel', { encoding: 'utf8' }).trim();
    const featureName = getFeatureName();
    const mergeDir = mergeDirFor(repoRoot, featureName);
    fs.mkdirSync(mergeDir, { recursive: true });

    const existing = readMergeMarker(mergeDir);
    if (existing) {
        await handleResume(mergeDir, existing);
        return;
    }
    await runFreshUpdate(repoRoot, mergeDir);
}

if (require.main === module) {
    main().catch((err: Error) => {
        const message = err instanceof Error ? err.message : String(err);
        process.stderr.write(message + '\n');
        process.exit(1);
    });
}
