/**
 * The whole stylesheet, as one string written to `styles.css` beside the pages.
 *
 * It is hand-written rather than generated by a framework because #985 puts the framework, the
 * bundler and the markdown library out of scope: adding an API reference to an upstream project must
 * not grow that project's dependency surface, and this package's own build has to stay `tsc`.
 *
 * Colours are declared once as custom properties and redefined for dark mode, so a theme toggle is
 * one attribute on `<html>` and nothing else in the site knows about it.
 */
export class SiteStyles {
    static readonly CSS = `
:root {
    --bg: #ffffff;
    --bg-soft: #f6f7f9;
    --fg: #1d2129;
    --fg-soft: #5b6472;
    --line: #e2e5ea;
    --accent: #2f5cff;
    --code-bg: #f2f3f6;
    --badge-fg: #ffffff;
}
:root[data-theme='dark'] {
    --bg: #14171c;
    --bg-soft: #1b1f26;
    --fg: #e7eaf0;
    --fg-soft: #9aa4b2;
    --line: #2a2f38;
    --accent: #7f9bff;
    --code-bg: #10131a;
    --badge-fg: #14171c;
}
* { box-sizing: border-box; }
body {
    margin: 0;
    background: var(--bg);
    color: var(--fg);
    font: 15px/1.6 -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
}
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
code, pre { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 13px; }
code { background: var(--code-bg); padding: 1px 4px; border-radius: 3px; }
pre { background: var(--code-bg); padding: 12px; border-radius: 6px; overflow-x: auto; }
pre code { background: none; padding: 0; }
table { border-collapse: collapse; width: 100%; margin: 12px 0; }
th, td { border: 1px solid var(--line); padding: 6px 10px; text-align: left; vertical-align: top; }
th { background: var(--bg-soft); }
hr { border: 0; border-top: 1px solid var(--line); margin: 24px 0; }
blockquote { margin: 12px 0; padding: 4px 14px; border-left: 3px solid var(--line); color: var(--fg-soft); }

.site { display: grid; grid-template-columns: 260px minmax(0, 1fr) 360px; gap: 0; min-height: 100vh; }
.pane-nav { border-right: 1px solid var(--line); padding: 20px 16px; background: var(--bg-soft); }
.pane-body { padding: 28px 32px; min-width: 0; }
.pane-cards { border-left: 1px solid var(--line); padding: 20px 16px; background: var(--bg-soft); }
.pane-cards-inner { position: sticky; top: 20px; }

.site-title { font-weight: 700; font-size: 15px; margin-bottom: 4px; display: block; color: var(--fg); }
.site-version { color: var(--fg-soft); font-size: 12px; margin-bottom: 16px; }
.nav-group { margin-bottom: 10px; }
.nav-group > summary { cursor: pointer; font-weight: 600; font-size: 12px; letter-spacing: .06em; text-transform: uppercase; color: var(--fg-soft); }
.nav-group ul { list-style: none; margin: 6px 0 0; padding: 0 0 0 4px; }
.nav-group li { margin: 2px 0; }
.nav-group a { display: flex; gap: 6px; align-items: center; padding: 3px 6px; border-radius: 4px; color: var(--fg); }
.nav-group a.current { background: var(--accent); color: var(--badge-fg); }
.nav-group a.current .badge { background: var(--badge-fg); color: var(--accent); }

.badge { font-size: 10px; font-weight: 700; letter-spacing: .04em; padding: 1px 5px; border-radius: 3px; background: var(--accent); color: var(--badge-fg); }
.op-head { display: flex; gap: 10px; align-items: center; flex-wrap: wrap; margin-bottom: 4px; }
.op-path { background: var(--code-bg); padding: 3px 8px; border-radius: 4px; }

.card { border: 1px solid var(--line); border-radius: 8px; background: var(--bg); margin-bottom: 16px; }
.card-head { display: flex; justify-content: space-between; align-items: center; padding: 8px 12px; border-bottom: 1px solid var(--line); font-size: 11px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; color: var(--fg-soft); }
.card-body { padding: 12px; }
.card-body pre { margin: 0; }
button { font: inherit; font-size: 11px; cursor: pointer; background: none; border: 1px solid var(--line); border-radius: 4px; padding: 2px 8px; color: var(--fg-soft); }
button:hover { color: var(--fg); }
.tabs { display: flex; gap: 4px; flex-wrap: wrap; padding: 8px 12px 0; }
.tab[aria-selected='true'] { border-color: var(--accent); color: var(--accent); }
.sample[hidden] { display: none; }

.field { border-top: 1px solid var(--line); padding: 10px 0; }
.field-head { display: flex; gap: 8px; align-items: baseline; flex-wrap: wrap; }
.field-name { font-weight: 600; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
.field-type { color: var(--fg-soft); font-size: 12px; }
.field-required { color: #c0392b; font-size: 11px; font-weight: 700; letter-spacing: .04em; }
.field-doc { margin: 4px 0 0; color: var(--fg-soft); }
.field-children { margin-left: 16px; border-left: 1px solid var(--line); padding-left: 12px; }
.chips { margin-top: 6px; font-size: 12px; color: var(--fg-soft); }
.chip { display: inline-block; background: var(--code-bg); border: 1px solid var(--line); border-radius: 10px; padding: 0 8px; margin: 2px 4px 2px 0; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
.variant { border: 1px solid var(--line); border-radius: 8px; padding: 10px 14px; margin: 12px 0; }
.variant-head { font-weight: 600; }
details.disclosure > summary { cursor: pointer; color: var(--fg-soft); font-size: 12px; }

@media (max-width: 1100px) {
    .site { grid-template-columns: 1fr; }
    .pane-nav, .pane-cards { border: 0; }
    .pane-cards-inner { position: static; }
}
`;
}
