// ---------------------------------------------------------------------------
// `webpieces.mergeprocess.md` — ONE template, TWO inputs.
//
// The merge-process doc used to live as a template literal inside pr-gate's `merge-start.ts`, and was
// written ONLY when a 3-point merge actually conflicted. `webpieces.git-workflow.md` links to it
// unconditionally, so in every tree that had not yet hit a conflict that link pointed at nothing —
// measured in six of nine governed repos.
//
// The cure is not "write it from one more place". It is to make the doc a rules-config TEMPLATE like
// every other instruct-ai doc, so `InstructAiDocSet` delivers it as part of git-workflow.md's LINK
// CLOSURE, and to give that template one renderer with two possible inputs:
//
//   new ReferenceMergeRun()  the tree has no conflicted merge — the doc reads as the PROCESS
//   new MergeRun(...)        pr-gate's conflict handback — the doc reads as a LIVE handback
//
// Two inputs, one output shape: there is exactly one spelling of the merge process, and the delivered
// copy cannot drift from it because the delivered copy IS it.
// ---------------------------------------------------------------------------

import { MERGE_EXPLANATION_FILE } from './constants';

/** The rules-config template name, and the file name it lands under in `.webpieces/instruct-ai/`. */
export const MERGE_PROCESS_DOC = 'webpieces.mergeprocess.md';

const REFERENCE_RUN_STATE = `**Reference copy — no conflicted 3-point merge is in progress in this tree.** It is written beside
\`webpieces.git-workflow.md\` on every \`wp-*\` command, so the link from that doc always resolves.

When a 3-point merge DOES conflict, \`pnpm wp-start-upsert-pr\` (or \`pnpm wp-start-update\`) rewrites
this file in place with the branch you are standing on, that run's absolute \`MERGE_DIR\`, the exact
finish command for the flow you started, and the list of conflicted files. Until that happens, read
what follows as the PROCESS and not as a live handback: \`<feature>Squash\` stands for the transient
branch a conflicted merge puts you on, and \`MERGE_DIR\` for that run's
\`.webpieces/merge-info/<feature>/merge-<n>/\` directory.`;

const REFERENCE_FILE_LIST =
    '*(none — no conflicted merge is in progress; the live copy lists this run\'s conflicted files here)*';

/**
 * The values one merge run stamps into the doc, plus the one rendering that depends on WHICH state
 * this is.
 *
 * `ReferenceMergeRun` below is not a second document — it is these same fields standing for "no run in
 * progress", which is exactly what a reader of the delivered copy has to be told before following the
 * steps. One class and its subclass, so there is one merge process and two things it can be about.
 */
export class MergeRun {
    // eslint-disable-next-line @typescript-eslint/max-params -- the five values one merge run stamps in
    constructor(
        /** The `wp-start-*` command that produced this state. */
        readonly startCommand: string,
        /** Its paired `wp-finish-*` command — the ONLY way out of a conflicted merge. */
        readonly finishCommand: string,
        /** The transient `<feature>Squash` branch the merge put the caller on. */
        readonly squashBranch: string,
        /** Absolute path of this run's `merge-<n>/` context dir. */
        readonly mergeDir: string,
        /** Markdown bullet list of the conflicted files. */
        readonly fileList: string,
    ) {}

    /** The doc's opening block: a LIVE conflict handback naming this run's branch and dir. */
    runState(): string {
        return `This file was generated by \`pnpm ${this.startCommand}\` when the 3-point squash-merge hit conflicts.\n` +
            'It is the single source of truth for the merge process — follow it exactly.\n\n' +
            `You are on branch \`${this.squashBranch}\` with conflict markers in the working tree.\n` +
            `\`MERGE_DIR = ${this.mergeDir}\``;
    }
}

/** The state of a tree with NO conflicted merge in it — what the delivered reference copy describes. */
export class ReferenceMergeRun extends MergeRun {
    constructor() {
        super('wp-start-upsert-pr', 'wp-finish-upsert-pr', '<feature>Squash', 'MERGE_DIR', REFERENCE_FILE_LIST);
    }

    override runState(): string {
        return REFERENCE_RUN_STATE;
    }
}

/** Substitutes one `MergeRun` (and the fixed explanation-file name) into the merge-process template. */
export class MergeProcessText {
    constructor(private readonly template: string, private readonly explanationFile: string = MERGE_EXPLANATION_FILE) {}

    render(run: MergeRun): string {
        return this.template
            .replace(/\{\{RUN_STATE\}\}/g, run.runState())
            .replace(/\{\{SQUASH_BRANCH\}\}/g, run.squashBranch)
            .replace(/\{\{MERGE_DIR\}\}/g, run.mergeDir)
            .replace(/\{\{EXPLANATION_FILE\}\}/g, this.explanationFile)
            .replace(/\{\{FINISH_COMMAND\}\}/g, run.finishCommand)
            .replace(/\{\{START_COMMAND\}\}/g, run.startCommand)
            .replace(/\{\{FILE_LIST\}\}/g, run.fileList);
    }
}
