import * as path from 'path';
import { injectable, bindingScopeValues } from 'inversify';

import { findConfigFile } from './config-file';
import { WEBPIECES_TMP_DIR } from './constants';
import { DotWebpieces, dotWebpieces } from './state-dir';

// The single instruct-ai home under `.webpieces/`. Kept here (not just in load-template) so callers
// building AI-facing messages can render the ABSOLUTE doc path from a resolved repo root.
export const INSTRUCT_AI_DIR = `${WEBPIECES_TMP_DIR}/instruct-ai`;
// The instruct-ai leaf under a resolved `.webpieces` dir. LOCAL scope — see instructAiDocPath.
export const INSTRUCT_AI_LEAF = 'instruct-ai';

/**
 * Resolves the single repo root that owns the `.webpieces/` tree, and renders absolute paths beneath
 * it.
 *
 * `.webpieces/` MUST live at the repo root — never in a CWD-dependent subdirectory. A tool invoked
 * from a subdir (a nested package, a `services/*` app) that naively joined `.webpieces` onto its own
 * cwd would scatter stray `.webpieces` trees across the tree — the exact bug this prevents. Every
 * writer of `.webpieces/...` (logs, instruct-ai docs, sync cache, merge/pr state) MUST anchor its
 * path here rather than at `process.cwd()`.
 */
@injectable(bindingScopeValues.Singleton)
export class RepoRootFinder {
    constructor(private readonly dotDir: DotWebpieces = dotWebpieces) {}

    /**
     * The repo root for `startDir`. Resolution order (first hit wins):
     *   1. Directory holding webpieces.config.json — the webpieces workspace root, and the exact
     *      anchor the hook runner already uses. Walks UP from startDir, so a subdir resolves to root.
     *   2. git toplevel — the repo root when no config is present yet (e.g. the installer runs before
     *      webpieces.config.json exists). Asked via `DotWebpieces.treeRoot`, which is the ONE
     *      `git rev-parse` tree-root resolver in this repo (memoized, fails closed). This class used to
     *      carry its own byte-identical `spawnSync` copy, with a comment claiming to "mirror"
     *      runner.ts's — a mirror that had already drifted, since runner.ts had moved the call to
     *      effective-tree.ts. There is one implementation now, so a mirror cannot drift.
     *   3. `startDir` — last resort (git unavailable / not a repo / no config). Best-effort only.
     *
     * Step 1 is deliberately FIRST and deliberately not identity: config walk-up climbs PAST a nested
     * clone's `.git` to the outer webpieces root (repo-root.spec.ts pins that), and in a linked worktree
     * it answers with the WORKTREE, because `webpieces.config.json` is TRACKED IN GIT and therefore part
     * of the BRANCH — a branch may change its own rules. See state-dir.ts for that boundary, and
     * `EffectiveTreeResolver` for the different question ("which tree is this, and is it ours") that
     * must NOT be answered from the config file.
     */
    resolveRepoRoot(startDir: string): string {
        const configPath = findConfigFile(startDir);
        if (configPath !== null) return path.dirname(configPath);
        const gitRoot = this.dotDir.treeRoot(startDir);
        if (gitRoot !== null) return gitRoot;
        return startDir;
    }

    /**
     * Absolute path to an instruct-ai doc. Hand THIS to the AI in a violation/fix message — never a
     * bare `.webpieces/instruct-ai/...` relative path, which an AI whose cwd is a subdirectory would
     * resolve against the wrong directory and fail to open.
     *
     * LOCAL scope: these docs are regenerated by every `wp-*` command, so under a shared path seven
     * agents would rewrite one file concurrently for no benefit — the content is version-scoped and
     * identical, and a doc the AI is told to open must never be mid-truncation. Per-worktree it has one
     * writer. TemplateWriter additionally writes it atomically and skips the write entirely when the
     * bytes already match.
     */
    instructAiDocPath(repoRoot: string, docName: string): string {
        return this.dotDir.localFile(repoRoot, INSTRUCT_AI_LEAF, docName);
    }

    /** Absolute instruct-ai doc path resolved directly from `startDir` (resolveRepoRoot + join). */
    docPathFrom(startDir: string, docName: string): string {
        return this.instructAiDocPath(this.resolveRepoRoot(startDir), docName);
    }

}
