import { injectable, bindingScopeValues } from 'inversify';
import * as fs from 'node:fs';
import { RepositoryPath } from './repository-path';
import { createHash } from 'node:crypto';
import {
    ConfigObject,
    OwnedRuleDefinition,
    RuleContribution,
    SafeguardDefinition,
} from '@webpieces/rules-sdk';
import { AtomicFile, InformAiError } from '@webpieces/tooling-common';
import { PackPolicyFilesResult, SelectedPolicyPack } from './pack-policy-files';

export const RULE_LOCK_FILE = '.webpieces/rules.lock.json';
export const RULE_CATALOG_FILE = '.webpieces/instruct-ai/rules-catalog.md';

class LockedOwnedRule {
    constructor(
        readonly id: string,
        readonly schemaApiVersion: number,
    ) {}
}

class LockedRulePack {
    readonly package: string;
    readonly config: string;
    readonly packageName: string;
    readonly packageVersion: string;
    readonly manifestApiVersion: number;
    readonly ownedRules: readonly LockedOwnedRule[];
    readonly contributions: readonly RuleContribution[];
    readonly safeguards: readonly SafeguardDefinition[];

    constructor(
        pack: SelectedPolicyPack,
        readonly manifestDigest: string,
    ) {
        this.package = pack.declaration.package;
        this.config = pack.declaration.config;
        this.packageName = pack.manifest.packageName;
        this.packageVersion = pack.manifest.packageVersion;
        this.manifestApiVersion = pack.manifest.apiVersion;
        this.ownedRules = pack.manifest.ownedRules.map(
            (definition: OwnedRuleDefinition) =>
                new LockedOwnedRule(definition.id, definition.schemaApiVersion),
        );
        this.contributions = pack.manifest.contributions;
        this.safeguards = pack.manifest.safeguards;
    }
}

class RuleLock {
    readonly schemaVersion = 1;
    constructor(readonly packs: readonly LockedRulePack[]) {}
}

export class RuleArtifactContents {
    constructor(
        readonly lock: string,
        readonly catalog: string,
    ) {}
}

/** One resolved owner/contributor registry produces both deterministic committed artifacts. */
@injectable(bindingScopeValues.Singleton)
export class RulePackArtifacts {
    constructor(private readonly atomic: AtomicFile) {}

    paths(root: string): readonly string[] {
        const repository = new RepositoryPath(root);
        return [repository.resolve(RULE_LOCK_FILE), repository.resolve(RULE_CATALOG_FILE)];
    }

    render(resolved: PackPolicyFilesResult): RuleArtifactContents {
        const selected = [...resolved.selected].sort(
            (a: SelectedPolicyPack, b: SelectedPolicyPack) =>
                a.manifest.packageName < b.manifest.packageName
                    ? -1
                    : a.manifest.packageName > b.manifest.packageName
                      ? 1
                      : 0,
        );
        const locks = selected.map(
            (pack: SelectedPolicyPack) => new LockedRulePack(pack, this.digest(pack.manifest)),
        );
        const rows: string[] = [];
        for (const pack of selected) {
            for (const definition of pack.manifest.ownedRules) {
                rows.push(
                    this.policyRow(pack, definition, resolved.values[definition.id], selected),
                );
            }
            for (const safeguard of pack.manifest.safeguards) {
                rows.push(
                    `| ${this.cell(safeguard.id)} | ${this.cell(pack.manifest.packageName)} | ${safeguard.activation} safeguard | — | ${this.cell(safeguard.description)} | Owner safety invariant |`,
                );
            }
        }
        const catalog = [
            '# Declared rule catalog',
            '',
            'Generated by `pnpm wp-rules-sync` from the selected installed manifests and explicit owner config files.',
            'Configurable policies require every required setting even when mode is `OFF`. Fixed safeguards have no config switch.',
            '',
            '| Policy | Owner | Status / contributors | Config file | Description | Remediation |',
            '| --- | --- | --- | --- | --- | --- |',
            ...rows,
            '',
        ].join('\n');
        return new RuleArtifactContents(this.stable(new RuleLock(locks)), catalog);
    }

    check(root: string, resolved: PackPolicyFilesResult): void {
        const contents = this.render(resolved);
        const errors: string[] = [];
        for (const artifact of [
            [RULE_LOCK_FILE, contents.lock],
            [RULE_CATALOG_FILE, contents.catalog],
        ]) {
            const filename = new RepositoryPath(root).resolve(artifact[0]);
            if (!fs.existsSync(filename)) errors.push(`Missing ${filename}.`);
            else if (fs.readFileSync(filename, 'utf8') !== artifact[1]) {
                errors.push(
                    `${filename} disagrees with the root declaration, installed manifests, or explicit owner config.`,
                );
            }
        }
        if (errors.length) {
            throw new InformAiError(
                `Rule artifacts need repair:\n${errors.map((error: string) => `• ${error}`).join('\n')}\nRun pnpm wp-rules-sync, review the generated diff, and commit the lock and catalog.`,
            );
        }
    }

    write(root: string, resolved: PackPolicyFilesResult): readonly string[] {
        const contents = this.render(resolved),
            changed: string[] = [];
        for (const artifact of [
            [RULE_LOCK_FILE, contents.lock],
            [RULE_CATALOG_FILE, contents.catalog],
        ]) {
            const filename = new RepositoryPath(root).resolve(artifact[0]);
            if (this.atomic.writeIfChanged(filename, artifact[1])) changed.push(filename);
        }
        return changed;
    }

    private policyRow(
        pack: SelectedPolicyPack,
        definition: OwnedRuleDefinition,
        config: ConfigObject,
        selected: readonly SelectedPolicyPack[],
    ): string {
        const contributors = selected.flatMap((provider: SelectedPolicyPack) =>
            provider.manifest.contributions
                .filter((contribution: RuleContribution) => contribution.ruleId === definition.id)
                .map(
                    (contribution: RuleContribution) =>
                        `${provider.manifest.packageName}:${contribution.executionKind}`,
                ),
        );
        const status = `${String(config['mode'])}; ${contributors.join(', ')}`;
        const remediation = definition.help.remediation.replaceAll(
            '{configFile}',
            pack.declaration.config,
        );
        return [
            definition.id,
            pack.manifest.packageName,
            status,
            pack.declaration.config,
            definition.help.description,
            remediation,
        ]
            .map((text: string) => this.cell(text))
            .join(' | ')
            .replace(/^/, '| ')
            .concat(' |');
    }

    private cell(value: string): string {
        return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
    }

    // webpieces-disable no-any-unknown -- canonical serialization accepts only the manifest's data boundary.
    private digest(value: unknown): string {
        return createHash('sha256').update(this.stable(value)).digest('hex');
    }

    // webpieces-disable no-any-unknown -- JSON keys are sorted recursively; functions must stay in runtime modules.
    private stable(value: unknown): string {
        return JSON.stringify(this.canonical(value), null, 2) + '\n';
    }

    // webpieces-disable no-any-unknown -- recursively narrow arbitrary manifest data before serialization.
    private canonical(value: unknown): unknown {
        if (value === null || ['string', 'boolean', 'number'].includes(typeof value)) return value;
        // webpieces-disable no-any-unknown -- external JSON or runtime exports are validated before policy execution
        if (Array.isArray(value)) return value.map((entry: unknown) => this.canonical(entry));
        if (typeof value !== 'object') {
            throw new InformAiError(
                'Rule manifests must contain only serializable data. Keep executable functions in the declared implementation modules.',
            );
        }
        // webpieces-disable no-any-unknown -- external JSON or runtime exports are validated before policy execution
        const record = value as Record<string, unknown>;
        return Object.fromEntries(
            Object.keys(record)
                .sort()
                .filter((key: string) => record[key] !== undefined)
                .map((key: string) => [key, this.canonical(record[key])]),
        );
    }
}
