import * as fs from 'fs';
import * as path from 'path';
import { toError } from './to-error';

// ---------------------------------------------------------------------------
// SWEEP DANGLING `node_modules/.bin/wp-*` SYMLINKS.
//
// THE DEFECT. pnpm's linker ADDS a link for every entry in the current manifest's `bin` map, but it never
// sweeps `.bin` for orphans left behind by a PREVIOUS version of the SAME package. `@webpieces/pr-gate`
// and `@webpieces/ai-hook-rules` are upgraded, never removed, so nothing ever triggers a delete: every
// bin either package has EVER shipped stays linked forever, pointing at a script that is no longer on
// disk. A scan of nine clones on ONE machine found 18 distinct dangling `wp-*` names.
//
// THE DEFECT IS ONGOING, AND A ROUTINE RENAME PRODUCES IT. Measured on this repo's own upgrade to
// 0.4.728, DURING the session that wrote this file: PR #743 hard-renamed one `wp-*` command with no alias,
// so the new manifest declares `wp-sync-main` and no longer declares its predecessor. One `pnpm install`
// later, `.bin` held the NEW link created that minute AND the predecessor's link still sitting there from
// the previous install, dangling — reproduced independently in two separate trees of this repo. So this is
// not a historical mess left by a deleted feature that a one-time migration could mop up: it is
// regenerated by the most ordinary change a package can make, on every clone, every time. That is the
// argument for the call site below — the sweep has to ride a path that runs ROUTINELY, because the defect
// is created routinely.
//
// The predecessor's NAME is deliberately not written here, and DO NOT WRITE IT BACK IN. Two reasons, and
// the second is the one that matters. First, nothing in the code needs it: the predicate below is
// STRUCTURAL — a `wp-*` entry whose link target does not resolve — so naming one particular retired
// command would invite a reader to think the sweep is a list of known dead names somebody has to keep up
// to date. Second, a retired command named in tracked source is exactly how a dead name outlives its
// tooling: it gets copied into a cure string, and an agent reading that cure at the moment every other
// route is closed is handed a command that does not exist. That is the very defect this module cleans up
// one level out, and there is no longer an automated scan standing behind this paragraph — the reader is.
// PR #743 and the issue this shipped under carry the literal name; nothing in the tree needs to.
//
// WHY IT MATTERS MORE THAN TIDINESS. `ls node_modules/.bin` lists them, so a dangling entry ADVERTISES a
// capability that does not exist — a human and an AI were both misled by that listing before checking the
// link target — and the failure it eventually produces is self-referential and useless:
// `Command "wp-authorize" not found / Did you mean "pnpm wp-authorize"?`. This is `upgrade-shim.ts`'s own
// governing principle one level out: an entry pointing at a missing file is WORSE than absence.
//
// WHY A PREFIX AND NOT A NAME LIST. A hardcoded list of retired bin names would go stale in exactly the
// way the symlinks did — the list assembled from the two names that prompted this would have caught 2 of
// the 18, and it would NOT have caught the rename above, which had not happened yet when the list would
// have been written. That is the general case: the next orphan is always created by a release later than
// any list. A name list is also unwriteable here on purpose — see the note above about naming dead
// commands in source. The predicate is structural instead — a `wp-` prefixed entry that is a SYMLINK whose target
// does not exist — so it needs no maintenance and cannot miss a name nobody has thought of. The prefix is
// the whole safety story: another package's bins are never touched.
//
// WHY NOT A postinstall HOOK. `setupDebugging.md` records the postinstall approach as ABANDONED in this
// repo. The call site is the `wp-*` startup pass that regenerates `.webpieces/instruct-ai/*` — see
// TemplateWriter — and that placement is the load-bearing half of the fix. This is not a tidy-up for one
// repo: every developer's machine has this graveyard, and a cure that only cleans the tree somebody happens
// to run it in is worthless. Riding the pass EVERY `wp-*` command takes is what makes the RELEASED sweep
// reach every clone on every machine, healing each one the next time any `wp-*` command runs there.
//
// NOT ALSO CALLED FROM `wp-upgrade-shim`, though it would read naturally there (that bin already deletes a
// retired FILE on the same principle). `upgrade-shim.ts` may import only `fs`/`path` so it still runs on a
// tree too broken to load the rule engine: this package's barrel would pull in inversify and the config
// loader, and a subpath import would resolve against the INSTALLED rules-config, which is a release behind
// the local source — so a spawned `wp-upgrade-shim` would die on module resolution, in the one command an
// L0-blocked session has left. Its header records that, and points here.
//
// DEPENDENCY-FREE ANYWAY: `fs`, `path` and `toError`. No inversify (see StaleBinSweeper), so this module
// stays cheap for the startup path it runs on and importable by anything that later needs it.
// ---------------------------------------------------------------------------

// The one place the prefix is spelled. Everything outside it belongs to some other package.
const WP_BIN_PREFIX = 'wp-';

/**
 * One dangling entry the sweep ACTED ON: what was linked, the target that was not there, and — when the
 * removal itself failed — why. Data-only (per CLAUDE.md).
 *
 * `failure` exists because the removal is an `fs.rmSync`, not just a probe: an unwritable `.bin` (EACCES,
 * a read-only mount) would otherwise heal silently-never while the tree kept advertising a command that
 * does not exist, which is the precise defect this module exists to remove. Not thrown — the sweep is a
 * courtesy and must never fail the `wp-*` command that called it — so the diagnostic rides back here and
 * {@link StaleBinSweeper.report} states both outcomes.
 */
export class StaleBinRemoval {
    name: string;    // the bin name as it appeared in .bin (e.g. 'wp-authorize')
    target: string;  // the link target that does not exist, as recorded in the symlink
    failure: string; // '' = removed; non-empty = still there, and this is why

    constructor(name: string, target: string, failure = '') {
        this.name = name;
        this.target = target;
        this.failure = failure;
    }
}

/**
 * Removes `node_modules/.bin/wp-*` entries whose symlink target is gone.
 *
 * Deliberately NOT `@injectable`: decorating it would import inversify, and this module must stay loadable
 * by `wp-upgrade-shim` on a tree that cannot build a DI container (see the header). Callers use the shared
 * {@link staleBinSweeper} instance, which is also what makes {@link sweepOnce}'s memo process-wide.
 */
export class StaleBinSweeper {
    // Roots already swept in THIS process. `writeTemplate` is called several times per `wp-*` command (once
    // per instruct-ai doc), and a sweep that reported per call would print the same removals repeatedly.
    private readonly swept = new Set<string>();

    /** Where the bins live for a tree. Public so a test can point at a fixture without guessing the layout. */
    binDir(repoRoot: string): string {
        return path.join(repoRoot, 'node_modules', '.bin');
    }

    /**
     * Sweep once per root per process, returning what was removed ([] on every later call for the same
     * root, and [] when there was nothing to remove — the two are indistinguishable to a caller ON PURPOSE,
     * because both mean "say nothing").
     */
    sweepOnce(repoRoot: string): StaleBinRemoval[] {
        if (this.swept.has(repoRoot)) return [];
        this.swept.add(repoRoot);
        return this.sweep(repoRoot);
    }

    /**
     * Remove every dangling `wp-*` symlink under the tree's `.bin`, returning what went. [] when the
     * directory does not exist (a linked worktree with no install of its own is the common case) or when
     * everything there resolves.
     *
     * BEST EFFORT, PER ENTRY. A `.bin` that cannot be read, or one entry that cannot be removed, must never
     * take down the `wp-*` command that called this — the sweep is a courtesy, not the command's job.
     */
    sweep(repoRoot: string): StaleBinRemoval[] {
        const dir = this.binDir(repoRoot);
        const removed: StaleBinRemoval[] = [];
        for (const name of this.entries(dir)) {
            if (!name.startsWith(WP_BIN_PREFIX)) continue;
            const removal = this.removeIfDangling(path.join(dir, name), name);
            if (removal !== null) removed.push(removal);
        }
        return removed;
    }

    /**
     * The lines a caller prints for a sweep. [] for an empty sweep, so REMOVING NOTHING IS SILENT — this
     * runs on every `wp-*` command and the common case must add no noise at all.
     *
     * Rendered here rather than at each call site so the two callers cannot describe the same act
     * differently; each still chooses its own output channel and its own leading icon convention.
     */
    report(removed: readonly StaleBinRemoval[]): string[] {
        if (removed.length === 0) return [];
        const gone = removed.filter((r: StaleBinRemoval): boolean => r.failure === '');
        const stuck = removed.filter((r: StaleBinRemoval): boolean => r.failure !== '');
        const lines: string[] = [];
        if (gone.length > 0) {
            lines.push(`✅ @webpieces: removed ${gone.length} dangling node_modules/.bin/wp-* symlink(s) left by an earlier release:`);
            for (const r of gone) lines.push(`     ${r.name} -> ${r.target} (target missing)`);
            lines.push('   They pointed at scripts this release no longer ships, so they could only ever fail on execution.');
        }
        // A failed removal is STATED, never quietly dropped: the entry is still there, still advertising a
        // command that does not exist, and only a human can fix an unwritable .bin.
        if (stuck.length > 0) {
            lines.push(`⚠️  @webpieces: ${stuck.length} dangling node_modules/.bin/wp-* symlink(s) could NOT be removed:`);
            for (const r of stuck) lines.push(`     ${r.name} -> ${r.target} (target missing; ${r.failure})`);
            lines.push('   They still advertise commands this release does not ship. Nothing else is affected — remove them by hand.');
        }
        return lines;
    }

    // The directory listing, or [] when there is no .bin (or it cannot be read).
    private entries(dir: string): string[] {
        // webpieces-disable no-unmanaged-exceptions -- chokepoint: an unreadable .bin means "nothing to sweep", never a failed wp-* command
        // eslint-disable-next-line @webpieces/no-unmanaged-exceptions
        try {
            if (!fs.existsSync(dir)) return [];
            return fs.readdirSync(dir);
        } catch (err: unknown) {
            const error = toError(err);
            void error; // best effort: no readable .bin means there is nothing to sweep
            return [];
        }
    }

    /**
     * Remove ONE entry if — and only if — it is a symlink whose target does not exist. Returns what was
     * acted on, with `failure` set when the entry was dangling but could not be removed; `null` when the
     * entry was not a dangling `wp-*` link at all.
     */
    private removeIfDangling(full: string, name: string): StaleBinRemoval | null {
        const target = this.danglingTarget(full);
        if (target === null) return null;
        // webpieces-disable no-unmanaged-exceptions -- chokepoint: an unremovable entry is REPORTED, never fatal to the wp-* command that called the sweep
        // eslint-disable-next-line @webpieces/no-unmanaged-exceptions
        try {
            fs.rmSync(full, { force: true });
            return new StaleBinRemoval(name, target);
        } catch (err: unknown) {
            const error = toError(err);
            return new StaleBinRemoval(name, target, error.message);
        }
    }

    /**
     * The link target of a DANGLING symlink, or `null` when this entry is not one — a real file, a live
     * link, or something we cannot stat. `existsSync` FOLLOWS symlinks, so a false answer on a path `lstat`
     * calls a link is exactly the dangling case, with no need to resolve the target ourselves.
     *
     * Split from the removal so the two catches mean different things: an unreadable entry is simply not
     * ours to touch, while a failed REMOVAL is a fact worth printing.
     */
    private danglingTarget(full: string): string | null {
        // webpieces-disable no-unmanaged-exceptions -- chokepoint: an entry we cannot stat is not ours to touch
        // eslint-disable-next-line @webpieces/no-unmanaged-exceptions
        try {
            if (!fs.lstatSync(full).isSymbolicLink()) return null;
            if (fs.existsSync(full)) return null;
            return fs.readlinkSync(full);
        } catch (err: unknown) {
            const error = toError(err);
            void error; // best effort: an entry we cannot read is left exactly as it is
            return null;
        }
    }
}

// The shared instance — the memo in `sweepOnce` is per-instance, so every caller must use this one.
export const staleBinSweeper = new StaleBinSweeper();
