export const builtInRuleNames: readonly string[] = [
    'no-any-unknown',
    'no-implicit-any',
    'max-file-lines',
    'validate-ts-in-src',
    'no-js-files',
    'no-destructure',
    'require-return-type',
    'no-unmanaged-exceptions',
    'catch-error-pattern',
    'no-shell-substitution',
    'no-symbol-di-tokens',
    'branch-creation-guard',
    'pr-creation-guard',
    'pr-merge-cleanup',
    'no-direct-main-update',
];
